In [16]:
import numpy as np

def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-2:-1]*0.5+0.5
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y

def sigmoid(val):
    if val>20:
        return 1.0
    if val<-1000:
        return 0.0
    return np.exp(val)/(1.0+np.exp(val))

def activation(val, threshold = 0.0):
    activation_func = np.vectorize(lambda x: sigmoid(x)*2.0-1.0)
    return activation_func(val)
    
n, dimension, train_x, train_y = read_data('classification.txt')
train_x, train_y

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]), array([[0.],
        [1.],
        [0.],
        ...,
        [1.],
        [0.],
        [0.]]))

In [17]:


def predict(n, train_x, train_y, W):
    output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
    return np.array(output).reshape(-1,1)

def get_accuracy(error):
#     return 1.0-np.sum([1.0 if np.sum(np.abs(x))>0.0 else 0.0 for x in error])/error.shape[0]
    return 1.0-(np.abs(error)>0.0).sum().astype('float')/error.shape[0]

def perceptron(n, dimension, train_x, train_y, max_epoch, learning_rate):
    weight=np.zeros((1,dimension))

    for epoch in range(max_epoch):
        error=predict(n, train_x, train_y, weight)-train_y
        
        accuracy = get_accuracy(error)
        
        delta = error*learning_rate*train_x
        
        for i in range(n):
            weight-=np.array([delta[i,:]*train_y[i,:]])

        print 'Epoch #%d: accuracy_rate=%.2f'%(epoch+1,accuracy), weight,delta, np.sum(error**2), np.sum(np.abs(error))

        if np.sum(np.abs(error))<1.0:
            break
            
    return weight, accuracy, error

weight, accuracy, error = perceptron(n, dimension, train_x, train_y, max_epoch=1000, learning_rate=1e-3)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f' % accuracy

Epoch #1: accuracy_rate=0.68 [[0.47728312 0.21003415 0.23245456 0.645     ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.77913692e-04 -1.92510086e-05 -5.06711124e-04 -1.00000000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.15506403e-04 -1.53543644e-04 -1.27549458e-05 -1.00000000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 645.0 645.0
Epoch #2: accuracy_rate=0.68 [[0.70116904 0.30700167 0.34028204 0.95642981]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.10868956e-04 -9.00958928e-06 -2.37143893e-04 -4.68006091e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.92482593e-04 -8.71159753e-05 -7.23676683e-06 -5.67369468e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 152.27123739700733

Epoch #18: accuracy_rate=0.68 [[1.51937755 0.65158073 0.72780494 2.16487815]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.76364279e-05 -8.25296614e-07 -2.17228605e-05 -4.28703052e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.84184353e-05 -1.44214367e-05 -1.19799583e-06 -9.39240231e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 2.2790074346278786 34.220912718677866
Epoch #19: accuracy_rate=0.68 [[1.54028467 0.66020017 0.73759955 2.197353  ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.55224845e-05 -7.78941781e-07 -2.05027422e-05 -4.04623881e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.62890286e-05 -1.37871927e-05 -1.14530886e-06 -8.97933145e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000

Epoch #35: accuracy_rate=0.68 [[1.77693423 0.75717896 0.84817604 2.57095366]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.84565532e-05 -4.04717761e-07 -1.06526882e-05 -2.10231978e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.77034975e-05 -8.25149004e-06 -6.85455327e-07 -5.37403558e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.6970480078123564 17.99102476944355
Epoch #36: accuracy_rate=0.68 [[1.78785195 0.76162761 0.85326538 2.58846191]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.79060704e-05 -3.92646701e-07 -1.03349625e-05 -2.03961626e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.70492140e-05 -8.05661161e-06 -6.69266680e-07 -5.24711503e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000000

Epoch #51: accuracy_rate=0.68 [[1.92275889 0.81641845 0.9160725  2.80684875]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.23049321e-05 -2.69824193e-07 -7.10211725e-06 -1.40161068e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.00958176e-05 -5.98554166e-06 -4.97221884e-07 -3.89826731e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.3587139448389037 12.509194134037182
Epoch #52: accuracy_rate=0.68 [[1.9302734  0.8194607  0.91956674 2.81912571]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.20497388e-05 -2.64228281e-07 -6.95482570e-06 -1.37254253e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.97639147e-05 -5.88668435e-06 -4.89009758e-07 -3.83388345e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000

Epoch #69: accuracy_rate=0.68 [[2.03962044 0.86361638 0.97036579 2.99914425]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.87479982e-06 -1.94607795e-07 -5.12232561e-06 -1.01089662e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.54905388e-05 -4.61385882e-06 -3.83275516e-07 -3.00491685e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.21093084611740445 9.344269014905592
Epoch #70: accuracy_rate=0.68 [[2.04517607 0.86585419 0.97294447 3.00835967]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.73756140e-06 -1.91598412e-07 -5.04311483e-06 -9.95264281e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.52989702e-05 -4.55680008e-06 -3.78535619e-07 -2.96775560e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000

Epoch #86: accuracy_rate=0.68 [[2.12457395 0.89777702 1.00977442 3.14080376]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.98921929e-06 -1.53260533e-07 -4.03401290e-06 -7.96116902e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.27972080e-05 -3.81164992e-06 -3.16635629e-07 -2.48245373e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.14341404925164808 7.555173393219338
Epoch #87: accuracy_rate=0.68 [[2.12902806 0.89956462 1.01183929 3.14827511]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.90201529e-06 -1.51348312e-07 -3.98368080e-06 -7.86183807e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.26691501e-05 -3.77350787e-06 -3.13467150e-07 -2.45761256e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000

Epoch #103: accuracy_rate=0.68 [[2.19400525 0.92560377 1.04194737 3.25777454]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.74461243e-06 -1.25968628e-07 -3.31565511e-06 -6.54348199e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.09349070e-05 -3.25696337e-06 -2.70557545e-07 -2.12119713e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.10461976391216501 6.348070065409962
Epoch #104: accuracy_rate=0.68 [[2.19772014 0.92709031 1.04366792 3.26406369]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.68451482e-06 -1.24650800e-07 -3.28096819e-06 -6.47502695e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-1.08429550e-05 -3.22957543e-06 -2.68282416e-07 -2.10335990e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #122: accuracy_rate=0.68 [[2.25903158 0.95159092 1.07205214 3.36831628]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.77698110e-06 -1.04750279e-07 -2.75716108e-06 -5.44128785e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-9.42810796e-06 -2.80816308e-06 -2.33275485e-07 -1.82890220e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.07784493604887158 5.391112298167636
Epoch #123: accuracy_rate=0.68 [[2.26216361 0.95284081 1.07350152 3.37366508]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.73463403e-06 -1.03821687e-07 -2.73271935e-06 -5.39305182e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-9.36079281e-06 -2.78811325e-06 -2.31609936e-07 -1.81584414e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #140: accuracy_rate=0.68 [[2.31178704 0.97262206 1.09645773 3.45871401]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.11061230e-06 -9.01380551e-08 -2.37254869e-06 -4.68225105e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-8.35367134e-06 -2.48814201e-06 -2.06691178e-07 -1.62047868e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.06123101756786981 4.720445147363538
Epoch #141: accuracy_rate=0.68 [[2.31451272 0.97370741 1.09771825 3.46340213]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.07876802e-06 -8.94397695e-08 -2.35416892e-06 -4.64597837e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-8.30146769e-06 -2.47259314e-06 -2.05399526e-07 -1.61035200e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #157: accuracy_rate=0.68 [[2.35564169 0.99006974 1.1167338  3.53435466]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.62648487e-06 -7.95220441e-08 -2.09312173e-06 -4.13079885e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-7.55062001e-06 -2.24895307e-06 -1.86821635e-07 -1.46469956e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.05014344767801571 4.2260183356594645
Epoch #158: accuracy_rate=0.68 [[2.3580692  0.9910346  1.11785584 3.53855485]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.60137683e-06 -7.89714718e-08 -2.07862996e-06 -4.10219919e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-7.50839615e-06 -2.23637669e-06 -1.85776909e-07 -1.45650880e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #175: accuracy_rate=0.68 [[2.39710845 1.00653832 1.13589633 3.60629445]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.22011748e-06 -7.06111658e-08 -1.85857603e-06 -3.66792033e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-6.85957752e-06 -2.04312598e-06 -1.69723478e-07 -1.33064836e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.041504361685105705 3.805541486066465
Epoch #176: accuracy_rate=0.68 [[2.39928345 1.00740135 1.13690119 3.61007911]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.20007517e-06 -7.01716753e-08 -1.84700808e-06 -3.64509085e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-6.82505283e-06 -2.03284280e-06 -1.68869249e-07 -1.32395113e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #192: accuracy_rate=0.68 [[2.43247309 1.0205613  1.15223195 3.66797185]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.90890510e-06 -6.37868591e-08 -1.67895157e-06 -3.31342947e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-6.31838547e-06 -1.88193187e-06 -1.56333004e-07 -1.22566576e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.03531689662935479 3.4796487276204138
Epoch #193: accuracy_rate=0.68 [[2.43445318 1.02134585 1.1531464  3.67143409]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.89237496e-06 -6.34243840e-08 -1.66941076e-06 -3.29460058e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-6.28932293e-06 -1.87327559e-06 -1.55613922e-07 -1.22002809e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #209: accuracy_rate=0.68 [[2.46479044 1.03335824 1.16715449 3.72459783]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.65026681e-06 -5.81154042e-08 -1.52967163e-06 -3.01882387e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.85971167e-06 -1.74531582e-06 -1.44984242e-07 -1.13669038e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.030468148699790268 3.20590947172158
Epoch #210: accuracy_rate=0.68 [[2.4666074  1.03407721 1.16799333 3.72778899]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.63641058e-06 -5.78115630e-08 -1.52167415e-06 -3.00304074e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.83489218e-06 -1.73792333e-06 -1.44370144e-07 -1.13187579e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #226: accuracy_rate=0.68 [[2.49454006 1.04512357 1.18088693 3.77694864]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.43206726e-06 -5.33306954e-08 -1.40373199e-06 -2.77028059e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.46574975e-06 -1.62797421e-06 -1.35236617e-07 -1.06026806e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.026591623840960286 2.9726784381040607
Epoch #227: accuracy_rate=0.68 [[2.49621851 1.04578694 1.18166158 3.77990867]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.42029237e-06 -5.30724941e-08 -1.39693580e-06 -2.75686824e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.44429430e-06 -1.62158371e-06 -1.34705754e-07 -1.05610605e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #242: accuracy_rate=0.68 [[2.52053086 1.05539079 1.19288088 3.82286197]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.25583178e-06 -4.94661803e-08 -1.30201302e-06 -2.56953707e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.14239597e-06 -1.53166325e-06 -1.27236018e-07 -9.97542599e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.02360806646697098 2.782606955043836
Epoch #243: accuracy_rate=0.68 [[2.52209679 1.05600904 1.19360341 3.82563351]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.24562040e-06 -4.92422637e-08 -1.29611925e-06 -2.55790565e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-5.12350965e-06 -1.52603796e-06 -1.26768722e-07 -9.93878954e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #260: accuracy_rate=0.68 [[2.54775911 1.06613532 1.20544258 3.8711395 ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.08454859e-06 -4.57102597e-08 -1.20315239e-06 -2.37443454e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.82328545e-06 -1.43661615e-06 -1.19340408e-07 -9.35640259e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.020838276534152083 2.5962783719660205
Epoch #261: accuracy_rate=0.68 [[2.54921507 1.06670952 1.20611419 3.87372617]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.07575533e-06 -4.55174399e-08 -1.19807713e-06 -2.36441845e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.80676610e-06 -1.43169586e-06 -1.18931677e-07 -9.32435771e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #277: accuracy_rate=0.68 [[2.5717686  1.07559997 1.21651658 3.91386218]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.94406573e-06 -4.26297327e-08 -1.12206899e-06 -2.21441555e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.55767466e-06 -1.35750394e-06 -1.12768519e-07 -8.84116014e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.018664772158880023 2.4421694182483566
Epoch #278: accuracy_rate=0.68 [[2.57313387 1.07613789 1.21714621 3.91629586]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.93636039e-06 -4.24607691e-08 -1.11762165e-06 -2.20563868e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.54299879e-06 -1.35313273e-06 -1.12405400e-07 -8.81269128e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #294: accuracy_rate=0.68 [[2.59432346 1.08448293 1.22691738 3.95412726]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.82051141e-06 -3.99204171e-08 -1.05075635e-06 -2.07367925e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.32093021e-06 -1.28698958e-06 -1.06910856e-07 -8.38191375e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.016828274257718115 2.305587074522923
Epoch #295: accuracy_rate=0.68 [[2.59560859 1.08498882 1.22750993 3.95642529]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.81370650e-06 -3.97711982e-08 -1.04682871e-06 -2.06592803e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.30780109e-06 -1.28307907e-06 -1.06586008e-07 -8.35644537e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #311: accuracy_rate=0.68 [[2.61558838 1.09285056 1.23672138 3.99220615]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.71103936e-06 -3.75198994e-08 -9.87571654e-07 -1.94898357e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.10852009e-06 -1.22372320e-06 -1.01655287e-07 -7.96987208e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.01526125151542172 2.1836884961833185
Epoch #312: accuracy_rate=0.68 [[2.61680215 1.09332796 1.23728093 3.99438307]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.70498787e-06 -3.73872015e-08 -9.84078876e-07 -1.94209053e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-4.09670192e-06 -1.22020316e-06 -1.01362875e-07 -7.94694673e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #327: accuracy_rate=0.68 [[2.63454817 1.10030519 1.24546105 4.02625322]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.61885333e-06 -3.54984318e-08 -9.34364047e-07 -1.84397777e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.92757937e-06 -1.16982998e-06 -9.71783509e-08 -7.61887602e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.013986507583004276 2.080345437452478
Epoch #328: accuracy_rate=0.68 [[2.63570161 1.10075851 1.24599269 4.02832743]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.61340375e-06 -3.53789327e-08 -9.31218678e-07 -1.83777035e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.91682095e-06 -1.16662559e-06 -9.69121601e-08 -7.59800640e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #343: accuracy_rate=0.68 [[2.6525861  1.10739217 1.25377444 4.05872921]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.53564331e-06 -3.36737915e-08 -8.86337184e-07 -1.74919622e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.76252104e-06 -1.12066734e-06 -9.30943861e-08 -7.29868925e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.01287183784610945 1.9864826109824683
Epoch #344: accuracy_rate=0.68 [[2.65368486 1.1078237  1.2542808  4.06071011]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.53071135e-06 -3.35656427e-08 -8.83490570e-07 -1.74357840e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.75268386e-06 -1.11773733e-06 -9.28509889e-08 -7.27960668e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #361: accuracy_rate=0.68 [[2.67188183 1.11496775 1.26266611 4.09356125]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.45123600e-06 -3.18228966e-08 -8.37619268e-07 -1.65305088e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.59329568e-06 -1.07026355e-06 -8.89073182e-08 -6.97041911e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.011776704975721083 1.8906665293863572
Epoch #362: accuracy_rate=0.68 [[2.6729249  1.1153771  1.26314672 4.09544686]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.44680406e-06 -3.17257125e-08 -8.35061257e-07 -1.64800261e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.58435816e-06 -1.06760150e-06 -8.86861810e-08 -6.95308174e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #379: accuracy_rate=0.68 [[2.69022157 1.12216269 1.27111591 4.12675559]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.37520139e-06 -3.01555997e-08 -7.93733884e-07 -1.56644259e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.43921166e-06 -1.02436960e-06 -8.50948856e-08 -6.67152073e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.01082151010399452 1.803800219695615
Epoch #380: accuracy_rate=0.68 [[2.69121427 1.12255199 1.27157325 4.12855481]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.37119818e-06 -3.00678167e-08 -7.91423322e-07 -1.56188267e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.43105401e-06 -1.02193985e-06 -8.48930446e-08 -6.65569621e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #396: accuracy_rate=0.68 [[2.70674534 1.12864078 1.27872795 4.15673689]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.31002221e-06 -2.87263419e-08 -7.56113993e-07 -1.49219932e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.30580707e-06 -9.84635031e-07 -8.17941152e-08 -6.41273717e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.010026786594771851 1.72888986287408
Epoch #397: accuracy_rate=0.68 [[2.7076947  1.12901284 1.27916526 4.15846157]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.30637005e-06 -2.86462568e-08 -7.54006051e-07 -1.48803927e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.29829454e-06 -9.82397423e-07 -8.16082361e-08 -6.39816406e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #412: accuracy_rate=0.68 [[2.72164983 1.13448044 1.28559316 4.18384032]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.25381335e-06 -2.74937863e-08 -7.23671558e-07 -1.42817381e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.18972809e-06 -9.50060891e-07 -7.89220245e-08 -6.18756250e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.00935963547339641 1.6639386313599358
Epoch #413: accuracy_rate=0.68 [[2.72256169 1.1348376  1.28601315 4.18550037]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.25045166e-06 -2.74200709e-08 -7.21731274e-07 -1.42434464e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.18275426e-06 -9.47983737e-07 -7.87494743e-08 -6.17403439e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #428: accuracy_rate=0.68 [[2.73597584 1.14009025 1.29219116 4.20994586]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.20199913e-06 -2.63575973e-08 -6.93765611e-07 -1.36915410e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.08183124e-06 -9.17923803e-07 -7.62523808e-08 -5.97825987e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.008759830904930021 1.6037621951189884
Epoch #429: accuracy_rate=0.68 [[2.73685301 1.14043363 1.29259513 4.21154601]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.19889511e-06 -2.62895320e-08 -6.91974045e-07 -1.36561842e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-3.07533934e-06 -9.15990190e-07 -7.60917546e-08 -5.96566662e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #446: accuracy_rate=0.68 [[2.75145424 1.14614781 1.29931908 4.23821107]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.14835585e-06 -2.51813003e-08 -6.62803973e-07 -1.30805096e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.96917587e-06 -8.84369386e-07 -7.34649989e-08 -5.75972645e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.00815446106658596 1.5411383449763179
Epoch #447: accuracy_rate=0.68 [[2.75229538 1.14647689 1.29970641 4.23974888]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.14550834e-06 -2.51188596e-08 -6.61160455e-07 -1.30480746e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.96316789e-06 -8.82579909e-07 -7.33163462e-08 -5.74807194e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #463: accuracy_rate=0.68 [[2.76549889 1.15164111 1.30578603 4.263912  ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.10169969e-06 -2.41582179e-08 -6.35875137e-07 -1.25490661e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.87036848e-06 -8.54939594e-07 -7.10202516e-08 -5.56805592e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.007641068022427953 1.4863898667179087
Epoch #464: accuracy_rate=0.68 [[2.7663086  1.15195772 1.30615884 4.2653953 ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.09906675e-06 -2.41004824e-08 -6.34355467e-07 -1.25190752e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.86476880e-06 -8.53271728e-07 -7.08817012e-08 -5.55719343e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #481: accuracy_rate=0.68 [[2.77980794 1.15723477 1.31237403 4.29014969]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.05606103e-06 -2.31574472e-08 -6.09533575e-07 -1.20292124e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.77293499e-06 -8.25919018e-07 -6.86094981e-08 -5.37905053e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.007150884691318715 1.4325685550088012
Epoch #482: accuracy_rate=0.68 [[2.78058681 1.15753915 1.3127326  4.29157938]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.05363028e-06 -2.31041455e-08 -6.08130606e-07 -1.20015247e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.76772322e-06 -8.24366692e-07 -6.84805457e-08 -5.36894054e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #498: accuracy_rate=0.68 [[2.79282939 1.16232239 1.31836861 4.31407293]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.01612927e-06 -2.22818182e-08 -5.86485903e-07 -1.15743641e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.68702119e-06 -8.00329582e-07 -6.64837711e-08 -5.21239149e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.006731896755002685 1.385250081128039
Epoch #499: accuracy_rate=0.68 [[2.79358119 1.16261605 1.31871469 4.31545549]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.01386916e-06 -2.22322582e-08 -5.85181420e-07 -1.15486200e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.68213940e-06 -7.98875539e-07 -6.63629831e-08 -5.20292159e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #515: accuracy_rate=0.68 [[2.80540529 1.16723351 1.32415754 4.33721984]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.78958318e-07 -2.14667286e-08 -5.65031704e-07 -1.11509631e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.60646464e-06 -7.76335803e-07 -6.44905962e-08 -5.05612466e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.00635030854483233 1.3410032964602596
Epoch #516: accuracy_rate=0.68 [[2.80613181 1.16751716 1.32449196 4.33855833]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.76851764e-07 -2.14205358e-08 -5.63815851e-07 -1.11269681e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.60188200e-06 -7.74970863e-07 -6.43772099e-08 -5.04723507e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #531: accuracy_rate=0.68 [[2.81686058 1.17170495 1.32943019 4.35834042]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.46251524e-07 -2.07495297e-08 -5.46154112e-07 -1.07784117e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.53509813e-06 -7.55079279e-07 -6.27248063e-08 -4.91768504e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.006021368623353313 1.3019039743275171
Epoch #532: accuracy_rate=0.68 [[2.81756481 1.17197977 1.32975432 4.35963996]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.44275855e-07 -2.07062070e-08 -5.45013803e-07 -1.07559076e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.53077225e-06 -7.53790818e-07 -6.26177732e-08 -4.90929354e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #547: accuracy_rate=0.68 [[2.82796914 1.17603917 1.33454285 4.3788548 ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.15549719e-07 -2.00762964e-08 -5.28433753e-07 -1.04286985e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.46767687e-06 -7.34997850e-07 -6.10566321e-08 -4.78689858e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.005718482193761179 1.2650536793045055
Epoch #548: accuracy_rate=0.68 [[2.82865238 1.17630569 1.33485729 4.38011762]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.13693299e-07 -2.00355886e-08 -5.27362271e-07 -1.04075527e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.46358647e-06 -7.33779523e-07 -6.09554251e-08 -4.77896385e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #563: accuracy_rate=0.68 [[2.83875112 1.1802442  1.33950483 4.39879732]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.86676941e-07 -1.94431703e-08 -5.11769065e-07 -1.00998190e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.40387784e-06 -7.15995303e-07 -5.94780812e-08 -4.66313867e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.00543891066779095 1.230262814100431
Epoch #564: accuracy_rate=0.68 [[2.83941458 1.1805029  1.33981015 4.40002547]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.84929461e-07 -1.94048513e-08 -5.10760461e-07 -1.00799141e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.40000392e-06 -7.14841454e-07 -5.93822304e-08 -4.65562388e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000

Epoch #581: accuracy_rate=0.68 [[2.85051341 1.18482959 1.34491754 4.42058821]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.56187629e-07 -1.87745966e-08 -4.94171352e-07 -9.75252621e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.33607572e-06 -6.95800431e-07 -5.78004833e-08 -4.53161339e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.005149305432443685 1.1933752752388975
Epoch #582: accuracy_rate=0.68 [[2.85115593 1.18508001 1.3452132  4.4217796 ]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.54551807e-07 -1.87387260e-08 -4.93227193e-07 -9.73389314e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.33242512e-06 -6.94713101e-07 -5.77101582e-08 -4.52453181e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #598: accuracy_rate=0.68 [[2.86128578 1.18902727 1.34987436 4.44057746]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.29159271e-07 -1.81819151e-08 -4.78571220e-07 -9.44465588e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.27558542e-06 -6.77783388e-07 -5.63037987e-08 -4.41427188e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.004897463831169934 1.160542015819941
Epoch #599: accuracy_rate=0.68 [[2.86190969 1.18927033 1.35016143 4.44173613]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.27619516e-07 -1.81481512e-08 -4.77682509e-07 -9.42711708e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.27212822e-06 -6.76753662e-07 -5.62182588e-08 -4.40756547e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #616: accuracy_rate=0.68 [[2.87235649 1.1933394  1.35496808 4.46115254]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.02246283e-07 -1.75917635e-08 -4.63037676e-07 -9.13809967e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.21498009e-06 -6.59732083e-07 -5.48042679e-08 -4.29670722e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.0046513235458825915 1.1277196872787794
Epoch #617: accuracy_rate=0.68 [[2.87296181 1.19357513 1.35524659 4.46227849]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.00799453e-07 -1.75600373e-08 -4.62202600e-07 -9.12161936e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.21171115e-06 -6.58758429e-07 -5.47233860e-08 -4.29036601e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.

Epoch #634: accuracy_rate=0.68 [[2.88310193 1.19752311 1.35991181 4.48115447]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.76936270e-07 -1.70367622e-08 -4.48429332e-07 -8.84980240e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.15763178e-06 -6.42650884e-07 -5.33853244e-08 -4.18546069e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.0044241101632049775 1.09673001015539
Epoch #635: accuracy_rate=0.68 [[2.88368974 1.19775192 1.36018224 4.48224953]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.75574336e-07 -1.70068975e-08 -4.47643256e-07 -8.83428910e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.15453592e-06 -6.41728781e-07 -5.33087248e-08 -4.17945521e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00

Epoch #651: accuracy_rate=0.68 [[2.89296832 1.20136306 1.36445082 4.49954736]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.54380796e-07 -1.65421628e-08 -4.35410843e-07 -8.59288109e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.10622608e-06 -6.27339690e-07 -5.21134159e-08 -4.08574185e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.004225153524945924 1.0690092739888288
Epoch #652: accuracy_rate=0.68 [[2.89354048 1.2015857  1.36471403 4.50061478]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.53092474e-07 -1.65139123e-08 -4.34667255e-07 -8.57820628e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.10328119e-06 -6.26462553e-07 -5.20405517e-08 -4.08002922e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #667: accuracy_rate=0.68 [[2.90201705 1.20488352 1.36861341 4.51643896]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.34254432e-07 -1.61008292e-08 -4.23794379e-07 -8.36362889e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.06011061e-06 -6.13604191e-07 -5.09724013e-08 -3.99628520e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.004050464292357546 1.0441884189708668
Epoch #668: accuracy_rate=0.68 [[2.90257522 1.20510064 1.36887017 4.51748163]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.33030163e-07 -1.60739832e-08 -4.23087760e-07 -8.34968368e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.05729779e-06 -6.12766394e-07 -5.09028050e-08 -3.99082879e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0

Epoch #684: accuracy_rate=0.68 [[2.91139176 1.20852954 1.37292572 4.53396232]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.13953153e-07 -1.56556600e-08 -4.12076959e-07 -8.13238431e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.01335168e-06 -5.99677038e-07 -4.98154658e-08 -3.90558035e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 0.0038770016353422265 1.0190673631957763
Epoch #685: accuracy_rate=0.68 [[2.91193578 1.20874108 1.37317596 4.53497994]] [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.12791930e-07 -1.56301966e-08 -4.11406729e-07 -8.11915723e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 ...
 [-2.01066956e-06 -5.98878168e-07 -4.97491033e-08 -3.90037747e-06]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.

In [3]:
# Epoch #1: accuracy_rate=67.75% [[ 0. -2.  0. ... -2.  0.  0.]]
# Epoch #2: accuracy_rate=100.00% [[0. 0. 0. ... 0. 0. 0.]]
# Weight matrix = [[0.95456624 0.42006829 0.46490911 1.29      ]]
# Accuracy rate=100.00%

In [15]:
(np.array([0.2,-0.1])>0.0).sum()

1