In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data[:, :2]
y = (iris.target != 0) * 1
X, y

(array([[5.1, 3.5],
        [4.9, 3. ],
        [4.7, 3.2],
        [4.6, 3.1],
        [5. , 3.6],
        [5.4, 3.9],
        [4.6, 3.4],
        [5. , 3.4],
        [4.4, 2.9],
        [4.9, 3.1],
        [5.4, 3.7],
        [4.8, 3.4],
        [4.8, 3. ],
        [4.3, 3. ],
        [5.8, 4. ],
        [5.7, 4.4],
        [5.4, 3.9],
        [5.1, 3.5],
        [5.7, 3.8],
        [5.1, 3.8],
        [5.4, 3.4],
        [5.1, 3.7],
        [4.6, 3.6],
        [5.1, 3.3],
        [4.8, 3.4],
        [5. , 3. ],
        [5. , 3.4],
        [5.2, 3.5],
        [5.2, 3.4],
        [4.7, 3.2],
        [4.8, 3.1],
        [5.4, 3.4],
        [5.2, 4.1],
        [5.5, 4.2],
        [4.9, 3.1],
        [5. , 3.2],
        [5.5, 3.5],
        [4.9, 3.6],
        [4.4, 3. ],
        [5.1, 3.4],
        [5. , 3.5],
        [4.5, 2.3],
        [4.4, 3.2],
        [5. , 3.5],
        [5.1, 3.8],
        [4.8, 3. ],
        [5.1, 3.8],
        [4.6, 3.2],
        [5.3, 3.7],
        [5. , 3.3],


In [4]:
# plt.figure(figsize=(10, 6))
# plt.scatter(X[y == 0][:, 0], X[y == 0][:, 1], color='b', label='0')
# plt.scatter(X[y == 1][:, 0], X[y == 1][:, 1], color='r', label='1')
# plt.legend();

In [5]:
def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-1]
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y.reshape(-1,1)
    
n, dimension, X, y = read_data('classification.txt')
y = np.squeeze(y)
y = (y+1.1).astype('int')/2
X, y

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]),
 array([1, 0, 1, ..., 1, 1, 1]))

In [6]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iter=100000):
        self.learning_rate = learning_rate
        self.num_iter = num_iter
    
    def add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def sigmoid(self, val):
        return 1 / (1 + np.exp(-val))
    
    def fit(self, X, y):
        X = self.add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            hypothesis = self.sigmoid(np.dot(X, self.theta))
            gradient = np.dot(X.T, (hypothesis - y)) / y.size
            self.theta -= self.learning_rate * gradient
            
#             hypothesis = self.sigmoid(np.dot(X, self.theta))

        return i
    
#     def predict_prob(self, X):
#         if self.fit_intercept:
#             X = self.__add_intercept(X)
    
#         return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(self, X):
        X = self.add_intercept(X)
        return self.sigmoid(np.dot(X, self.theta)).round()

In [7]:
model = LogisticRegression(learning_rate=0.1, num_iter=70000)

In [8]:
%time epoch=model.fit(X, y)
print epoch

CPU times: user 17.4 s, sys: 4.1 s, total: 21.5 s
Wall time: 3.77 s
69999


In [9]:
preds = model.predict(X).astype('int')
(preds == y).mean(), (preds==y).sum() ,  preds

(0.5295, 1059, array([1, 0, 1, ..., 0, 1, 1]))

In [10]:
model.theta, (preds==y).sum()*1.0/len(preds)

(array([-0.01575038, -0.17769619,  0.11445235,  0.07670126, -0.01575038]),
 0.5295)

In [11]:
# probs = model.predict_prob(X)
# probs