In [1]:
import numpy as np
from math import exp

def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-1:]
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y
    
n, dimension, train_x, train_y = read_data('classification.txt')
train_x, train_y

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]), array([[ 1.],
        [-1.],
        [ 1.],
        ...,
        [ 1.],
        [ 1.],
        [ 1.]]))

In [2]:
def activation(val):
    if val>20:
        return 1.0
    if val<-1000:
        return 0.0
    return np.exp(val)/(1.0+np.exp(val))

def predict(n, train_x, train_y, W):
    output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
    return np.array(output).reshape(-1,1)

In [5]:
def get_accuracy(error):
    return 100.0-100.0*np.sum([1.0 if np.sum(np.abs(x))>0.0 else 0.0 for x in error])/error.shape[0]

def perceptron(n, dimension, train_x, train_y, max_epoch, learning_rate):
    weight=np.zeros((1,dimension))

    for epoch in range(max_epoch):
        error=predict(n, train_x, train_y, weight)-train_y
        
        accuracy = get_accuracy(error)
        
        delta = error*learning_rate*train_x
        for i in range(n):
            try:
                weight-=np.array([delta[i,:]*train_y[i,:]])
            finally:
                print weight.shape,np.array([delta[i,:]*train_y[i,:]]).shape 
                print weight, np.array([delta[i,:]*train_y[i,:]])

        print 'Epoch #%d: accuracy_rate=%.2f%%'%(epoch+1,accuracy)

        if np.sum(error**2)<1.0:# or np.sum(np.abs(last_weight - weight))<1e-8:
            break
            
    return weight, accuracy, error

weight, accuracy = perceptron(n, dimension, train_x, train_y, max_epoch=7000, learning_rate=1e-3)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f%%' % accuracy

(1, 4) (1, 4)
[[0.00037504 0.0004887  0.00044283 0.0005    ]] [[-0.00037504 -0.0004887  -0.00044283 -0.0005    ]]
(1, 4) (1, 4)
[[0.00169191 0.00051758 0.0012029  0.002     ]] [[-1.31687054e-03 -2.88765129e-05 -7.60066686e-04 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.00208057 0.00101461 0.00161402 0.0025    ]] [[-0.00038866 -0.00049703 -0.00041112 -0.0005    ]]
(1, 4) (1, 4)
[[0.00217115 0.00124499 0.00187676 0.003     ]] [[-9.05791399e-05 -2.30374720e-04 -2.62738304e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.00222843 0.00127877 0.00194122 0.0035    ]] [[-5.72820597e-05 -3.37773275e-05 -6.44602461e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.00310859 0.00152664 0.00211856 0.005     ]] [[-0.00088016 -0.00024788 -0.00017734 -0.0015    ]]
(1, 4) (1, 4)
[[0.00426299 0.00171439 0.00301729 0.0065    ]] [[-0.0011544  -0.00018775 -0.00089873 -0.0015    ]]
(1, 4) (1, 4)
[[0.00507854 0.0023959  0.00399598 0.008     ]] [[-0.00081555 -0.0006815  -0.00097869 -0.0015    ]]
(1, 4) (1, 4)
[[0.0055713  0.00275383 0.

[[0.16689614 0.1561203  0.15279552 0.323     ]] [[-0.0010364  -0.00094792 -0.00100443 -0.0015    ]]
(1, 4) (1, 4)
[[0.16713315 0.15621299 0.15311721 0.3235    ]] [[-2.37006703e-04 -9.26868462e-05 -3.21691136e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.16735995 0.15769121 0.15397218 0.325     ]] [[-0.00022679 -0.00147822 -0.00085497 -0.0015    ]]
(1, 4) (1, 4)
[[0.16758508 0.15796688 0.1540306  0.3255    ]] [[-2.25137319e-04 -2.75672564e-04 -5.84277204e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.16797203 0.15816413 0.15406192 0.326     ]] [[-3.86945645e-04 -1.97253967e-04 -3.13199371e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.16924035 0.15819008 0.15526409 0.3275    ]] [[-1.26831841e-03 -2.59507341e-05 -1.20216876e-03 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.16977465 0.15914033 0.15572787 0.329     ]] [[-0.00053431 -0.00095025 -0.00046377 -0.0015    ]]
(1, 4) (1, 4)
[[0.17013754 0.15944204 0.15618964 0.3295    ]] [[-0.00036288 -0.0003017  -0.00046177 -0.0005    ]]
(1, 4) (1, 4)
[[0.17027939 0.15949122 

[[0.2989918  0.29661152 0.29626215 0.603     ]] [[-0.00025188 -0.00032393 -0.00045581 -0.0005    ]]
(1, 4) (1, 4)
[[0.29939681 0.29709327 0.29644491 0.6035    ]] [[-0.00040501 -0.00048175 -0.00018276 -0.0005    ]]
(1, 4) (1, 4)
[[0.29972544 0.2975209  0.29688481 0.604     ]] [[-0.00032863 -0.00042763 -0.0004399  -0.0005    ]]
(1, 4) (1, 4)
[[0.30042846 0.29885963 0.29800594 0.6055    ]] [[-0.00070303 -0.00133873 -0.00112113 -0.0015    ]]
(1, 4) (1, 4)
[[0.30104253 0.29957573 0.29822589 0.607     ]] [[-0.00061407 -0.0007161  -0.00021995 -0.0015    ]]
(1, 4) (1, 4)
[[0.30143048 0.29984254 0.29856201 0.6075    ]] [[-0.00038794 -0.00026681 -0.00033611 -0.0005    ]]
(1, 4) (1, 4)
[[0.30271366 0.30095221 0.29862038 0.609     ]] [[-1.28318296e-03 -1.10967270e-03 -5.83701002e-05 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.30399246 0.3018502  0.29888725 0.6105    ]] [[-0.0012788  -0.00089799 -0.00026687 -0.0015    ]]
(1, 4) (1, 4)
[[0.30406538 0.30199161 0.29890222 0.612     ]] [[-7.29227199e-05 -1.414

[[0.42823569 0.42714222 0.41577156 0.859     ]] [[-0.0005731  -0.00122552 -0.00057375 -0.0015    ]]
(1, 4) (1, 4)
[[0.42837422 0.42815652 0.41672022 0.8605    ]] [[-0.00013852 -0.0010143  -0.00094865 -0.0015    ]]
(1, 4) (1, 4)
[[0.42887289 0.42822756 0.41696949 0.861     ]] [[-4.98677065e-04 -7.10405555e-05 -2.49278001e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.42909638 0.42862353 0.41697818 0.8615    ]] [[-2.23484777e-04 -3.95963548e-04 -8.68938472e-06 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.42913223 0.42941784 0.41739233 0.863     ]] [[-3.58556133e-05 -7.94317575e-04 -4.14151879e-04 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.43001344 0.42990029 0.41822023 0.8645    ]] [[-0.00088121 -0.00048245 -0.0008279  -0.0015    ]]
(1, 4) (1, 4)
[[0.43005103 0.43071596 0.41881607 0.866     ]] [[-3.75901453e-05 -8.15669846e-04 -5.95833276e-04 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.43007175 0.4313737  0.41960073 0.8675    ]] [[-2.07206247e-05 -6.57734726e-04 -7.84659505e-04 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.4300

[[0.57510622 0.56988534 0.57041304 1.158     ]] [[-0.00062501 -0.00036584 -0.00110262 -0.0015    ]]
(1, 4) (1, 4)
[[0.575155   0.57017961 0.57066732 1.1585    ]] [[-4.87827748e-05 -2.94267472e-04 -2.54274308e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.57546964 0.57063659 0.57087171 1.159     ]] [[-0.00031464 -0.00045698 -0.0002044  -0.0005    ]]
(1, 4) (1, 4)
[[0.57586858 0.57082914 0.57221696 1.1605    ]] [[-0.00039894 -0.00019255 -0.00134525 -0.0015    ]]
(1, 4) (1, 4)
[[0.576123   0.57127117 0.57251206 1.161     ]] [[-0.00025442 -0.00044204 -0.0002951  -0.0005    ]]
(1, 4) (1, 4)
[[0.57640941 0.57155759 0.57264177 1.1615    ]] [[-0.00028641 -0.00028642 -0.0001297  -0.0005    ]]
(1, 4) (1, 4)
[[0.57778957 0.57261368 0.57264934 1.163     ]] [[-1.38015766e-03 -1.05608147e-03 -7.56868174e-06 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.57921102 0.57407693 0.57392768 1.1645    ]] [[-0.00142145 -0.00146325 -0.00127835 -0.0015    ]]
(1, 4) (1, 4)
[[0.57961599 0.57487004 0.57409551 1.166     ]] [[-0.000

[[0.71230194 0.70763653 0.70465432 1.4335    ]] [[-4.96772110e-05 -1.45102406e-04 -4.58599547e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.7124333  0.70777974 0.70503427 1.434     ]] [[-0.00013136 -0.00014321 -0.00037995 -0.0005    ]]
(1, 4) (1, 4)
[[0.7127101  0.70809912 0.70537285 1.4345    ]] [[-0.00027681 -0.00031938 -0.00033859 -0.0005    ]]
(1, 4) (1, 4)
[[0.7127639  0.70834449 0.70564419 1.435     ]] [[-5.38000908e-05 -2.45369730e-04 -2.71339905e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.71366085 0.70842851 0.7056631  1.4365    ]] [[-8.96943713e-04 -8.40162942e-05 -1.89096108e-05 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.71417173 0.70966245 0.70716051 1.438     ]] [[-0.00051088 -0.00123394 -0.0014974  -0.0015    ]]
(1, 4) (1, 4)
[[0.71461585 0.70972728 0.70723172 1.4385    ]] [[-4.44114769e-04 -6.48316384e-05 -7.12099943e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.71484656 0.70984663 0.70769573 1.439     ]] [[-0.00023071 -0.00011935 -0.00046401 -0.0005    ]]
(1, 4) (1, 4)
[[0.71499702 0.71009726 

[[0.84479876 0.84119775 0.83603816 1.688     ]] [[-0.00018221 -0.00044665 -0.0001705  -0.0005    ]]
(1, 4) (1, 4)
[[0.84497208 0.84147575 0.83624674 1.6885    ]] [[-0.00017331 -0.000278   -0.00020858 -0.0005    ]]
(1, 4) (1, 4)
[[0.84505765 0.84187335 0.836653   1.689     ]] [[-8.55752423e-05 -3.97607581e-04 -4.06264704e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.84536123 0.84193697 0.83671411 1.6895    ]] [[-3.03580297e-04 -6.36162197e-05 -6.11119893e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.84547935 0.84341359 0.8379022  1.691     ]] [[-0.00011812 -0.00147662 -0.00118809 -0.0015    ]]
(1, 4) (1, 4)
[[0.84549204 0.84361477 0.83805999 1.6915    ]] [[-1.26951905e-05 -2.01185732e-04 -1.57789463e-04 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.84600658 0.84404081 0.83837872 1.693     ]] [[-0.00051454 -0.00042603 -0.00031873 -0.0015    ]]
(1, 4) (1, 4)
[[0.84629333 0.84464723 0.8389157  1.6945    ]] [[-0.00028675 -0.00060642 -0.00053699 -0.0015    ]]
(1, 4) (1, 4)
[[0.84632726 0.84510869 0.83907634 1.695

(1, 4) (1, 4)
[[0.98242986 0.98709353 0.97205492 1.969     ]] [[-0.00064708 -0.00024587 -0.00044354 -0.0015    ]]
(1, 4) (1, 4)
[[0.98255272 0.98722334 0.97243554 1.9695    ]] [[-0.00012286 -0.00012981 -0.00038062 -0.0005    ]]
(1, 4) (1, 4)
[[0.98326438 0.98829298 0.97254753 1.971     ]] [[-0.00071167 -0.00106963 -0.00011199 -0.0015    ]]
(1, 4) (1, 4)
[[0.98381782 0.98962036 0.97366695 1.9725    ]] [[-0.00055343 -0.00132738 -0.00111942 -0.0015    ]]
(1, 4) (1, 4)
[[0.98417495 0.98997489 0.97376979 1.973     ]] [[-0.00035713 -0.00035453 -0.00010285 -0.0005    ]]
(1, 4) (1, 4)
[[0.98518243 0.99044559 0.97472073 1.9745    ]] [[-0.00100748 -0.0004707  -0.00095094 -0.0015    ]]
(1, 4) (1, 4)
[[0.9856508  0.99050139 0.97601049 1.976     ]] [[-4.68371144e-04 -5.58039525e-05 -1.28976207e-03 -1.50000000e-03]]
(1, 4) (1, 4)
[[0.98612974 0.99060192 0.97608279 1.9765    ]] [[-4.78935925e-04 -1.00530182e-04 -7.23008323e-05 -5.00000000e-04]]
(1, 4) (1, 4)
[[0.98735101 0.99131721 0.97642889 1.978  

[[1.04725258 1.04494485 1.03479215 2.09886773]] [[-2.28362096e-05 -6.07914310e-06 -1.71022105e-05 -5.36123167e-05]]
(1, 4) (1, 4)
[[1.0472629  1.04495967 1.03480158 2.0988846 ]] [[-1.03181350e-05 -1.48208287e-05 -9.43148647e-06 -1.68742586e-05]]
(1, 4) (1, 4)
[[1.04796941 1.04533483 1.03498529 2.09992247]] [[-0.00070651 -0.00037516 -0.00018371 -0.00103787]]
(1, 4) (1, 4)
[[1.04798316 1.04533803 1.03501125 2.09995019]] [[-1.37505435e-05 -3.20496875e-06 -2.59621421e-05 -2.77161230e-05]]
(1, 4) (1, 4)
[[1.0484431  1.04627532 1.03527123 2.10097594]] [[-0.00045994 -0.00093729 -0.00025998 -0.00102575]]
(1, 4) (1, 4)
[[1.04891208 1.04656681 1.03535676 2.10203242]] [[-4.68977140e-04 -2.91492693e-04 -8.55212524e-05 -1.05648077e-03]]
(1, 4) (1, 4)
[[1.04891416 1.04658707 1.03538131 2.1020795 ]] [[-2.08096059e-06 -2.02627261e-05 -2.45548882e-05 -4.70869916e-05]]
(1, 4) (1, 4)
[[1.04895326 1.04659395 1.03538203 2.10212629]] [[-3.91039788e-05 -6.87143153e-06 -7.16952349e-07 -4.67871006e-05]]
(1, 4)

[[1.13213067 1.13329674 1.12139114 2.27339139]] [[-0.00042542 -0.0003503  -0.00057526 -0.00103497]]
(1, 4) (1, 4)
[[1.13272076 1.13331648 1.12234599 2.27441985]] [[-5.90083857e-04 -1.97381655e-05 -9.54844575e-04 -1.02846078e-03]]
(1, 4) (1, 4)
[[1.13304095 1.13428851 1.12263421 2.27544765]] [[-0.0003202  -0.00097203 -0.00028822 -0.00102779]]
(1, 4) (1, 4)
[[1.13305108 1.13430138 1.12265301 2.27547349]] [[-1.01212960e-05 -1.28742488e-05 -1.88036400e-05 -2.58447871e-05]]
(1, 4) (1, 4)
[[1.13306511 1.13431308 1.12266268 2.27549118]] [[-1.40341128e-05 -1.16977047e-05 -9.66769784e-06 -1.76906544e-05]]
(1, 4) (1, 4)
[[1.13396601 1.13503916 1.12267103 2.27651744]] [[-9.00904243e-04 -7.26083339e-04 -8.34629182e-06 -1.02625845e-03]]
(1, 4) (1, 4)
[[1.13398159 1.13505596 1.12267317 2.27653434]] [[-1.55779201e-05 -1.67934150e-05 -2.14508885e-06 -1.68962014e-05]]
(1, 4) (1, 4)
[[1.13400143 1.13507071 1.1226791  2.27655835]] [[-1.98400893e-05 -1.47514511e-05 -5.93112518e-06 -2.40192038e-05]]
(1, 4)

[[1.20341532 1.2041935  1.18361971 2.41337835]] [[-1.20969204e-05 -2.71772086e-05 -7.47446370e-06 -4.63528944e-05]]
(1, 4) (1, 4)
[[1.20342453 1.20420918 1.18363134 2.41339721]] [[-9.20896143e-06 -1.56845456e-05 -1.16361910e-05 -1.88666595e-05]]
(1, 4) (1, 4)
[[1.20343894 1.204217   1.18365218 2.41342532]] [[-1.44034142e-05 -7.81852937e-06 -2.08371705e-05 -2.81105305e-05]]
(1, 4) (1, 4)
[[1.20344148 1.20425516 1.18365487 2.41348757]] [[-2.53930116e-06 -3.81547382e-05 -2.69153884e-06 -6.22439907e-05]]
(1, 4) (1, 4)
[[1.20428866 1.2050493  1.18402088 2.41450574]] [[-0.00084719 -0.00079414 -0.000366   -0.00101818]]
(1, 4) (1, 4)
[[1.20429899 1.20505866 1.18403481 2.41452167]] [[-1.03231286e-05 -9.35839731e-06 -1.39382899e-05 -1.59275577e-05]]
(1, 4) (1, 4)
[[1.20430128 1.20509849 1.18403942 2.4145669 ]] [[-2.29664362e-06 -3.98284086e-05 -4.60163059e-06 -4.52263025e-05]]
(1, 4) (1, 4)
[[1.20532257 1.20530614 1.18408067 2.41560454]] [[-1.02129112e-03 -2.07651421e-04 -4.12579113e-05 -1.03764

[[1.29066573 1.28692222 1.26735464 2.58480706]] [[-9.82342992e-06 -9.26429624e-06 -2.14823915e-05 -6.93785874e-05]]
(1, 4) (1, 4)
[[1.29120342 1.28722076 1.26800307 2.58583775]] [[-0.00053769 -0.00029854 -0.00064842 -0.00103069]]
(1, 4) (1, 4)
[[1.29120639 1.28725255 1.26800423 2.58591511]] [[-2.97244043e-06 -3.17904450e-05 -1.16492198e-06 -7.73517935e-05]]
(1, 4) (1, 4)
[[1.29121834 1.28727352 1.26801658 2.58594906]] [[-1.19542021e-05 -2.09721784e-05 -1.23457080e-05 -3.39494832e-05]]
(1, 4) (1, 4)
[[1.29126634 1.28756991 1.26836605 2.58701423]] [[-4.79917563e-05 -2.96394768e-04 -3.49474720e-04 -1.06517874e-03]]
(1, 4) (1, 4)
[[1.29128301 1.28758722 1.26836987 2.58703464]] [[-1.66701494e-05 -1.73052457e-05 -3.81720023e-06 -2.04028162e-05]]
(1, 4) (1, 4)
[[1.29129523 1.28760089 1.26837723 2.5870503 ]] [[-1.22261892e-05 -1.36708423e-05 -7.36148087e-06 -1.56652672e-05]]
(1, 4) (1, 4)
[[1.2920992  1.28776669 1.26918208 2.58807337]] [[-0.00080397 -0.0001658  -0.00080485 -0.00102306]]
(1, 4)

[[1.36443488 1.36138629 1.34533491 2.74407178]] [[-1.34917128e-05 -3.90441227e-06 -2.54794424e-05 -2.76460778e-05]]
(1, 4) (1, 4)
[[1.36522482 1.36222085 1.34545466 2.74509537]] [[-0.00078993 -0.00083457 -0.00011975 -0.00102359]]
(1, 4) (1, 4)
[[1.36536525 1.36265736 1.34626728 2.74612912]] [[-0.00014044 -0.0004365  -0.00081262 -0.00103375]]
(1, 4) (1, 4)
[[1.36629568 1.36348237 1.34647038 2.74714817]] [[-0.00093043 -0.00082501 -0.0002031  -0.00101906]]
(1, 4) (1, 4)
[[1.36630305 1.36349721 1.34649134 2.74717653]] [[-7.36504424e-06 -1.48482625e-05 -2.09599640e-05 -2.83595357e-05]]
(1, 4) (1, 4)
[[1.36693041 1.36365973 1.34684691 2.74821915]] [[-0.00062736 -0.00016251 -0.00035557 -0.00104261]]
(1, 4) (1, 4)
[[1.3671554  1.3637138  1.34705842 2.74929735]] [[-2.24990948e-04 -5.40694059e-05 -2.11508503e-04 -1.07820570e-03]]
(1, 4) (1, 4)
[[1.36717292 1.36371971 1.34708079 2.74933278]] [[-1.75191127e-05 -5.91296172e-06 -2.23730937e-05 -3.54267862e-05]]
(1, 4) (1, 4)
[[1.36718154 1.36373253 

[[1.43338027 1.43081943 1.41470446 2.87798364]] [[-2.11638806e-05 -1.45274961e-06 -2.09634027e-05 -6.23669230e-05]]
(1, 4) (1, 4)
[[1.43339207 1.43083873 1.41471213 2.87800521]] [[-1.17984732e-05 -1.92913003e-05 -7.67626579e-06 -2.15656672e-05]]
(1, 4) (1, 4)
[[1.43403368 1.43169368 1.41501839 2.8790275 ]] [[-0.00064161 -0.00085495 -0.00030625 -0.00102229]]
(1, 4) (1, 4)
[[1.4348776  1.43215996 1.41580107 2.88004425]] [[-0.00084392 -0.00046628 -0.00078268 -0.00101676]]
(1, 4) (1, 4)
[[1.4348873  1.4321695  1.41580864 2.88005492]] [[-9.70164921e-06 -9.53996153e-06 -7.56987599e-06 -1.06691644e-05]]
(1, 4) (1, 4)
[[1.43576948 1.4330307  1.41582699 2.88107808]] [[-8.82178818e-04 -8.61202437e-04 -1.83501826e-05 -1.02315379e-03]]
(1, 4) (1, 4)
[[1.43677905 1.43304737 1.41640029 2.88210547]] [[-1.00956889e-03 -1.66673209e-05 -5.73298303e-04 -1.02739052e-03]]
(1, 4) (1, 4)
[[1.4375135  1.43385067 1.41731261 2.88311717]] [[-0.00073445 -0.0008033  -0.00091232 -0.00101171]]
(1, 4) (1, 4)
[[1.4375

(1, 4) (1, 4)
[[1.5115666  1.50760003 1.48721396 3.02701353]] [[-0.00078074 -0.00083932 -0.00072928 -0.00101293]]
(1, 4) (1, 4)
[[1.51162202 1.50792656 1.4876774  3.02807024]] [[-5.5424994e-05 -3.2652527e-04 -4.6343608e-04 -1.0567122e-03]]
(1, 4) (1, 4)
[[1.51190914 1.5086176  1.4885141  3.02909239]] [[-0.00028711 -0.00069105 -0.0008367  -0.00102215]]
(1, 4) (1, 4)
[[1.51253866 1.50877467 1.48947433 3.03011614]] [[-0.00062953 -0.00015707 -0.00096023 -0.00102375]]
(1, 4) (1, 4)
[[1.51289588 1.50963978 1.49046768 3.03113097]] [[-0.00035722 -0.00086511 -0.00099335 -0.00101484]]
(1, 4) (1, 4)
[[1.51390518 1.50991931 1.49126956 3.03214778]] [[-0.00100929 -0.00027953 -0.00080188 -0.0010168 ]]
(1, 4) (1, 4)
[[1.5139981  1.51068453 1.49128324 3.03320284]] [[-9.29222194e-05 -7.65216785e-04 -1.36745208e-05 -1.05505781e-03]]
(1, 4) (1, 4)
[[1.51427845 1.51169081 1.49206274 3.03422004]] [[-0.00028035 -0.00100628 -0.0007795  -0.0010172 ]]
(1, 4) (1, 4)
[[1.51429234 1.51169853 1.49207954 3.03424102]

[[1.56113055 1.55443158 1.53900057 3.12955041]] [[-1.35161545e-06 -2.34745991e-06 -1.60468034e-06 -2.98611599e-06]]
(1, 4) (1, 4)
[[1.56113193 1.55443461 1.53900265 3.12955458]] [[-1.38198783e-06 -3.03048964e-06 -2.08536139e-06 -4.17149877e-06]]
(1, 4) (1, 4)
[[1.56113199 1.55443724 1.53900525 3.12955754]] [[-5.53458539e-08 -2.63319364e-06 -2.59998077e-06 -2.96011706e-06]]
(1, 4) (1, 4)
[[1.5611347  1.55444053 1.53900675 3.12956295]] [[-2.70822529e-06 -3.28272134e-06 -1.50091800e-06 -5.40979612e-06]]
(1, 4) (1, 4)
[[1.56113591 1.55444126 1.53900813 3.12956444]] [[-1.20835740e-06 -7.37080846e-07 -1.37409245e-06 -1.48519721e-06]]
(1, 4) (1, 4)
[[1.56113714 1.55444199 1.5390096  3.129566  ]] [[-1.23677007e-06 -7.29366556e-07 -1.47545315e-06 -1.56285436e-06]]
(1, 4) (1, 4)
[[1.56147628 1.55499538 1.53904172 3.13057704]] [[-3.39132802e-04 -5.53387177e-04 -3.21170477e-05 -1.01104177e-03]]
(1, 4) (1, 4)
[[1.56172498 1.55522142 1.5394662  3.1315886 ]] [[-0.00024871 -0.00022604 -0.00042448 -0.0

[[1.6284462  1.62129203 1.60150295 3.26418305]] [[-0.0002029  -0.00096567 -0.00024121 -0.00100527]]
(1, 4) (1, 4)
[[1.62915158 1.62222288 1.60201909 3.26518473]] [[-0.00070537 -0.00093085 -0.00051613 -0.00100168]]
(1, 4) (1, 4)
[[1.62953734 1.62279437 1.60273625 3.26618826]] [[-0.00038576 -0.00057149 -0.00071716 -0.00100353]]
(1, 4) (1, 4)
[[1.62980681 1.62297902 1.60273887 3.26721066]] [[-2.69475649e-04 -1.84650886e-04 -2.62338008e-06 -1.02239251e-03]]
(1, 4) (1, 4)
[[1.6304882  1.62343629 1.60371484 3.26821246]] [[-0.00068139 -0.00045727 -0.00097597 -0.0010018 ]]
(1, 4) (1, 4)
[[1.63115727 1.62360937 1.60403413 3.26922017]] [[-0.00066908 -0.00017308 -0.00031928 -0.00100771]]
(1, 4) (1, 4)
[[1.63115788 1.62360964 1.60404374 3.26923252]] [[-6.03778008e-07 -2.74345961e-07 -9.61543510e-06 -1.23496844e-05]]
(1, 4) (1, 4)
[[1.63131791 1.62432014 1.60461701 3.27023755]] [[-0.00016003 -0.0007105  -0.00057327 -0.00100503]]
(1, 4) (1, 4)
[[1.63194963 1.62460516 1.6050567  3.27124328]] [[-0.000

[[1.70027814 1.69592952 1.67513063 3.41188613]] [[-0.00068387 -0.00046776 -0.0006468  -0.00100291]]
(1, 4) (1, 4)
[[1.70068619 1.69603376 1.67577858 3.41289391]] [[-0.00040805 -0.00010424 -0.00064795 -0.00100778]]
(1, 4) (1, 4)
[[1.70068918 1.69603551 1.67578024 3.41289798]] [[-2.98897325e-06 -1.75056060e-06 -1.65975153e-06 -4.07209057e-06]]
(1, 4) (1, 4)
[[1.70150554 1.69680404 1.67592344 3.4139012 ]] [[-0.00081636 -0.00076854 -0.0001432  -0.00100322]]
(1, 4) (1, 4)
[[1.70222531 1.69749043 1.67671231 3.41490278]] [[-0.00071977 -0.00068639 -0.00078887 -0.00100158]]
(1, 4) (1, 4)
[[1.70281379 1.69770427 1.67758661 3.41590631]] [[-0.00058848 -0.00021384 -0.00087431 -0.00100353]]
(1, 4) (1, 4)
[[1.70368883 1.69865509 1.67802077 3.41690773]] [[-0.00087504 -0.00095081 -0.00043416 -0.00100142]]
(1, 4) (1, 4)
[[1.70369283 1.6986555  1.67802584 3.41691673]] [[-4.00587351e-06 -4.13161724e-07 -5.07067256e-06 -8.99707433e-06]]
(1, 4) (1, 4)
[[1.70423297 1.6990748  1.6788635  3.41791966]] [[-0.000

[[1.76056169 1.75845536 1.73092231 3.53432597]] [[-1.64027933e-06 -4.09112012e-06 -1.02438539e-06 -4.48005774e-06]]
(1, 4) (1, 4)
[[1.76056244 1.75845675 1.7309297  3.53433501]] [[-7.53929524e-07 -1.38885902e-06 -7.39430078e-06 -9.03377252e-06]]
(1, 4) (1, 4)
[[1.76056427 1.75845905 1.73093383 3.53434154]] [[-1.82880183e-06 -2.30875501e-06 -4.13043329e-06 -6.53083753e-06]]
(1, 4) (1, 4)
[[1.76128805 1.759158   1.73127063 3.53534461]] [[-0.00072378 -0.00069895 -0.0003368  -0.00100308]]
(1, 4) (1, 4)
[[1.76158924 1.75958195 1.73165077 3.53635304]] [[-0.00030119 -0.00042395 -0.00038014 -0.00100843]]
(1, 4) (1, 4)
[[1.76246124 1.7595897  1.73253534 3.53735612]] [[-8.71998510e-04 -7.74623609e-06 -8.84564519e-04 -1.00307942e-03]]
(1, 4) (1, 4)
[[1.76276852 1.75989935 1.73322047 3.53836238]] [[-0.00030728 -0.00030966 -0.00068513 -0.00100626]]
(1, 4) (1, 4)
[[1.76375282 1.76087388 1.73327154 3.53936446]] [[-9.84297514e-04 -9.74528603e-04 -5.10732442e-05 -1.00207923e-03]]
(1, 4) (1, 4)
[[1.7640

(1, 4) (1, 4)
[[1.83278262 1.82130644 1.80310077 3.67480745]] [[-7.52641801e-07 -1.08745109e-06 -1.02550942e-06 -1.21004640e-06]]
(1, 4) (1, 4)
[[1.83343619 1.82134621 1.80344923 3.67581672]] [[-6.53571004e-04 -3.97759194e-05 -3.48458907e-04 -1.00927036e-03]]
(1, 4) (1, 4)
[[1.83343872 1.82134737 1.80345139 3.67582021]] [[-2.53441926e-06 -1.15550887e-06 -2.16282432e-06 -3.49821183e-06]]
(1, 4) (1, 4)
[[1.83352471 1.82201146 1.80444852 3.67682339]] [[-8.59909658e-05 -6.64090764e-04 -9.97129404e-04 -1.00317639e-03]]
(1, 4) (1, 4)
[[1.8337776  1.82273245 1.80476582 3.67782972]] [[-0.00025289 -0.00072099 -0.00031729 -0.00100633]]
(1, 4) (1, 4)
[[1.83377966 1.82273372 1.80477242 3.67783991]] [[-2.05033800e-06 -1.27235652e-06 -6.60731862e-06 -1.01916234e-05]]
(1, 4) (1, 4)
[[1.83416706 1.82373753 1.80490734 3.67884431]] [[-0.0003874  -0.00100381 -0.00013492 -0.00100439]]
(1, 4) (1, 4)
[[1.83502935 1.82415934 1.80532931 3.67984765]] [[-0.0008623  -0.00042181 -0.00042197 -0.00100334]]
(1, 4) (

[[1.90998782 1.89981108 1.87859807 3.83161194]] [[-6.74569285e-06 -9.84732664e-07 -1.08161399e-06 -7.59453786e-06]]
(1, 4) (1, 4)
[[1.90998956 1.89981198 1.87860157 3.83161571]] [[-1.73971434e-06 -8.99989718e-07 -3.49891374e-06 -3.77027045e-06]]
(1, 4) (1, 4)
[[1.90999209 1.8998162  1.87860404 3.83162413]] [[-2.53337211e-06 -4.22009143e-06 -2.47125365e-06 -8.41888111e-06]]
(1, 4) (1, 4)
[[1.90999228 1.89982058 1.87860702 3.83162958]] [[-1.91705798e-07 -4.37775217e-06 -2.97609975e-06 -5.45346156e-06]]
(1, 4) (1, 4)
[[1.90999635 1.8998219  1.8786086  3.83163433]] [[-4.06754656e-06 -1.32374771e-06 -1.58856208e-06 -4.74815623e-06]]
(1, 4) (1, 4)
[[1.90999732 1.89982315 1.87860945 3.83163566]] [[-9.73354504e-07 -1.24802817e-06 -8.48777469e-07 -1.33352267e-06]]
(1, 4) (1, 4)
[[1.91099438 1.90028457 1.87930967 3.83263733]] [[-0.00099706 -0.00046142 -0.00070021 -0.00100167]]
(1, 4) (1, 4)
[[1.9109946  1.90028888 1.87931356 3.83264413]] [[-2.11849010e-07 -4.31934249e-06 -3.89673783e-06 -6.79945

[[1.97034158 1.96305438 1.94015558 3.94822843]] [[-0.00034728 -0.00028755 -0.00021512 -0.00101241]]
(1, 4) (1, 4)
[[1.97053475 1.96346289 1.94051731 3.9492389 ]] [[-0.00019317 -0.00040852 -0.00036174 -0.00101047]]
(1, 4) (1, 4)
[[1.97053516 1.96346849 1.94051926 3.94924496]] [[-4.11187796e-07 -5.59299175e-06 -1.94698485e-06 -6.06017084e-06]]
(1, 4) (1, 4)
[[1.9708349  1.9644419  1.94066505 3.95025014]] [[-0.00029974 -0.00097341 -0.00014579 -0.00100519]]
(1, 4) (1, 4)
[[1.97145301 1.96453101 1.94086446 3.95126151]] [[-6.18104907e-04 -8.91115457e-05 -1.99407228e-04 -1.01137033e-03]]
(1, 4) (1, 4)
[[1.97145366 1.96453739 1.94086696 3.95127065]] [[-6.46080500e-07 -6.37660452e-06 -2.49936010e-06 -9.13360790e-06]]
(1, 4) (1, 4)
[[1.9724307  1.96506812 1.94088908 3.952275  ]] [[-9.77041700e-04 -5.30735901e-04 -2.21250743e-05 -1.00435193e-03]]
(1, 4) (1, 4)
[[1.97313543 1.96597232 1.94188733 3.95327584]] [[-0.00070473 -0.0009042  -0.00099825 -0.00100084]]
(1, 4) (1, 4)
[[1.97313976 1.96597699 

(1, 4) (1, 4)
[[2.04840389 2.04235772 2.01700813 4.10400603]] [[-4.98145800e-06 -1.17542412e-06 -2.60629740e-06 -7.45818153e-06]]
(1, 4) (1, 4)
[[2.04840579 2.04235985 2.01701151 4.10401131]] [[-1.90531402e-06 -2.13132171e-06 -3.38424076e-06 -5.28275853e-06]]
(1, 4) (1, 4)
[[2.0484076  2.04236508 2.01701355 4.1040194 ]] [[-1.81183015e-06 -5.22963015e-06 -2.03084209e-06 -8.08734784e-06]]
(1, 4) (1, 4)
[[2.04892946 2.04271415 2.01767828 4.10502377]] [[-0.00052185 -0.00034906 -0.00066473 -0.00100437]]
(1, 4) (1, 4)
[[2.04934427 2.04280083 2.01846617 4.10603016]] [[-4.14809661e-04 -8.66812474e-05 -7.87893117e-04 -1.00639424e-03]]
(1, 4) (1, 4)
[[2.04996052 2.04289485 2.01869795 4.10704094]] [[-6.16250981e-04 -9.40227735e-05 -2.31779107e-04 -1.01077778e-03]]
(1, 4) (1, 4)
[[2.05083926 2.04310486 2.01968796 4.10804284]] [[-0.00087874 -0.00021001 -0.00099001 -0.0010019 ]]
(1, 4) (1, 4)
[[2.05084047 2.04310753 2.01969484 4.10806053]] [[-1.20777811e-06 -2.66627307e-06 -6.88103363e-06 -1.7689507

(1, 4) (1, 4)
[[2.09277601 2.07954356 2.05928574 4.19038245]] [[-0.00071394 -0.0001039  -0.00067461 -0.00100078]]
(1, 4) (1, 4)
[[2.09277632 2.07954396 2.05928602 4.19038306]] [[-3.05205144e-07 -3.93921416e-07 -2.81895843e-07 -6.08489698e-07]]
(1, 4) (1, 4)
[[2.09277647 2.07954419 2.05928621 4.19038335]] [[-1.56115898e-07 -2.35531754e-07 -1.83725945e-07 -2.91476716e-07]]
(1, 4) (1, 4)
[[2.09277684 2.07954499 2.05928782 4.19038741]] [[-3.64901968e-07 -7.98257486e-07 -1.60973214e-06 -4.05173675e-06]]
(1, 4) (1, 4)
[[2.09316702 2.07978244 2.05992259 4.19138866]] [[-0.00039018 -0.00023745 -0.00063477 -0.00100125]]
(1, 4) (1, 4)
[[2.09325    2.08072401 2.05997178 4.19239048]] [[-8.29787247e-05 -9.41564253e-04 -4.91893459e-05 -1.00182511e-03]]
(1, 4) (1, 4)
[[2.09382089 2.08144458 2.06026563 4.19339113]] [[-0.00057089 -0.00072057 -0.00029385 -0.00100064]]
(1, 4) (1, 4)
[[2.09382158 2.08144498 2.06026596 4.19339218]] [[-6.88072632e-07 -4.01329276e-07 -3.27994497e-07 -1.05863616e-06]]
(1, 4) (

[[2.17147468 2.1622028  2.13897841 4.35074327]] [[-0.0002827  -0.00064461 -0.00093577 -0.00100037]]
(1, 4) (1, 4)
[[2.17198843 2.16293458 2.13927246 4.35174397]] [[-0.00051375 -0.00073178 -0.00029405 -0.0010007 ]]
(1, 4) (1, 4)
[[2.17224775 2.16337059 2.13935513 4.35274731]] [[-2.59316884e-04 -4.36005292e-04 -8.26684514e-05 -1.00333779e-03]]
(1, 4) (1, 4)
[[2.17224782 2.16337069 2.13935522 4.35274742]] [[-7.54406021e-08 -1.03197620e-07 -9.06330311e-08 -1.09764792e-07]]
(1, 4) (1, 4)
[[2.17250029 2.16357524 2.139454   4.35375267]] [[-2.52468572e-04 -2.04552526e-04 -9.87846365e-05 -1.00525274e-03]]
(1, 4) (1, 4)
[[2.17258396 2.16435566 2.13991196 4.35475378]] [[-8.36742798e-05 -7.80412492e-04 -4.57957774e-04 -1.00110806e-03]]
(1, 4) (1, 4)
[[2.17300404 2.16447092 2.14027818 4.35575639]] [[-0.00042007 -0.00011527 -0.00036621 -0.00100261]]
(1, 4) (1, 4)
[[2.17300439 2.16447147 2.14027966 4.35575907]] [[-3.54353035e-07 -5.44559831e-07 -1.48164069e-06 -2.67715853e-06]]
(1, 4) (1, 4)
[[2.1730

[[2.23819427 2.23044057 2.20013397 4.48408775]] [[-4.75701733e-07 -1.05625698e-06 -1.79413131e-07 -1.44172357e-06]]
(1, 4) (1, 4)
[[2.23819456 2.23044133 2.20013443 4.48408892]] [[-2.93319706e-07 -7.57667615e-07 -4.59948372e-07 -1.16833708e-06]]
(1, 4) (1, 4)
[[2.23819492 2.23044194 2.20013456 4.48408964]] [[-3.59079682e-07 -6.16078655e-07 -1.25580458e-07 -7.21408171e-07]]
(1, 4) (1, 4)
[[2.23819508 2.23044239 2.20013588 4.48409142]] [[-1.62132142e-07 -4.50978837e-07 -1.32562521e-06 -1.77306338e-06]]
(1, 4) (1, 4)
[[2.23819518 2.2304425  2.20013782 4.48409353]] [[-9.83993168e-08 -1.02799391e-07 -1.93382845e-06 -2.11688314e-06]]
(1, 4) (1, 4)
[[2.23918587 2.23090257 2.20030227 4.48509413]] [[-0.00099069 -0.00046007 -0.00016445 -0.0010006 ]]
(1, 4) (1, 4)
[[2.23918614 2.23090262 2.20030253 4.48509443]] [[-2.69819261e-07 -5.28997842e-08 -2.62741869e-07 -2.98071539e-07]]
(1, 4) (1, 4)
[[2.24002235 2.23162552 2.20109241 4.48609457]] [[-0.00083621 -0.0007229  -0.00078987 -0.00100014]]
(1, 4)

[[2.31910685 2.30776742 2.27637524 4.64144255]] [[-1.82169165e-07 -9.89604347e-07 -3.58892209e-07 -1.19391798e-06]]
(1, 4) (1, 4)
[[2.31910725 2.30776745 2.27637644 4.64144388]] [[-4.04211248e-07 -3.32452827e-08 -1.20528828e-06 -1.33013928e-06]]
(1, 4) (1, 4)
[[2.31985994 2.30844219 2.27729391 4.64244402]] [[-0.00075269 -0.00067474 -0.00091747 -0.00100014]]
(1, 4) (1, 4)
[[2.32078188 2.30878403 2.27791595 4.64344437]] [[-0.00092194 -0.00034184 -0.00062204 -0.00100035]]
(1, 4) (1, 4)
[[2.32081859 2.30908413 2.27813636 4.64444963]] [[-3.67076978e-05 -3.00101996e-04 -2.20409048e-04 -1.00526159e-03]]
(1, 4) (1, 4)
[[2.32162685 2.30938388 2.27817316 4.6454512 ]] [[-8.08260868e-04 -2.99742702e-04 -3.68067008e-05 -1.00156764e-03]]
(1, 4) (1, 4)
[[2.32201538 2.30952684 2.2782492  4.64645592]] [[-3.88527765e-04 -1.42963672e-04 -7.60332486e-05 -1.00471968e-03]]
(1, 4) (1, 4)
[[2.32201554 2.30952702 2.27824929 4.64645612]] [[-1.54602154e-07 -1.83187877e-07 -9.59645655e-08 -2.01584796e-07]]
(1, 4)

(1, 4) (1, 4)
[[2.39253758 2.3772662  2.35214516 4.79481963]] [[-9.62739920e-09 -3.99996815e-07 -4.79745188e-07 -5.26170725e-07]]
(1, 4) (1, 4)
[[2.39331276 2.37793736 2.35231003 4.79582023]] [[-0.00077518 -0.00067116 -0.00016487 -0.00100061]]
(1, 4) (1, 4)
[[2.39331283 2.37793774 2.35231037 4.79582068]] [[-7.32739551e-08 -3.84087631e-07 -3.39511028e-07 -4.52260229e-07]]
(1, 4) (1, 4)
[[2.39331407 2.37793795 2.35231137 4.79582356]] [[-1.23432100e-06 -2.03591874e-07 -1.00843724e-06 -2.87599877e-06]]
(1, 4) (1, 4)
[[2.39331459 2.37793813 2.35231355 4.79582832]] [[-5.21661002e-07 -1.81858709e-07 -2.17985188e-06 -4.75771872e-06]]
(1, 4) (1, 4)
[[2.39374464 2.37853569 2.35242239 4.79682992]] [[-0.00043006 -0.00059756 -0.00010884 -0.0010016 ]]
(1, 4) (1, 4)
[[2.39374532 2.3785368  2.35242293 4.79683246]] [[-6.72033091e-07 -1.10676328e-06 -5.35993912e-07 -2.54361555e-06]]
(1, 4) (1, 4)
[[2.39422263 2.37908456 2.35253105 4.79783408]] [[-0.00047732 -0.00054776 -0.00010812 -0.00100161]]
(1, 4) (

[[2.44458095 2.43152638 2.40364384 4.8961199 ]] [[-1.26091414e-06 -3.75024392e-08 -3.35507205e-07 -1.33590389e-06]]
(1, 4) (1, 4)
[[2.44546729 2.43215561 2.40421049 4.89712013]] [[-0.00088634 -0.00062923 -0.00056665 -0.00100023]]
(1, 4) (1, 4)
[[2.44546801 2.43215643 2.40421138 4.89712295]] [[-7.14817089e-07 -8.23919354e-07 -8.87076753e-07 -2.81690475e-06]]
(1, 4) (1, 4)
[[2.4454681  2.43215655 2.4042115  4.89712309]] [[-9.38554370e-08 -1.19078379e-07 -1.26167127e-07 -1.46672317e-07]]
(1, 4) (1, 4)
[[2.4454682  2.43215681 2.40421187 4.89712349]] [[-9.29765935e-08 -2.58157273e-07 -3.71827861e-07 -3.95098922e-07]]
(1, 4) (1, 4)
[[2.44554661 2.43240118 2.40520657 4.89812462]] [[-7.84108825e-05 -2.44370195e-04 -9.94692395e-04 -1.00113184e-03]]
(1, 4) (1, 4)
[[2.4458041  2.43332564 2.40520991 4.89912607]] [[-2.57494575e-04 -9.24462230e-04 -3.34558973e-06 -1.00144896e-03]]
(1, 4) (1, 4)
[[2.44606554 2.43340299 2.40559282 4.90012984]] [[-2.61437269e-04 -7.73436847e-05 -3.82910789e-04 -1.00376

[[2.51858284 2.50636852 2.47470163 5.03846572]] [[-5.73150356e-08 -1.99582915e-06 -5.14793590e-07 -3.24779072e-06]]
(1, 4) (1, 4)
[[2.51858324 2.50636899 2.47470291 5.03846789]] [[-4.02731872e-07 -4.66644350e-07 -1.28805561e-06 -2.17800931e-06]]
(1, 4) (1, 4)
[[2.51900696 2.50712315 2.47502087 5.03946867]] [[-0.00042372 -0.00075416 -0.00031795 -0.00100077]]
(1, 4) (1, 4)
[[2.51900755 2.50712431 2.47502087 5.03947019]] [[-5.89930362e-07 -1.16551403e-06 -6.54318596e-09 -1.51911979e-06]]
(1, 4) (1, 4)
[[2.51930244 2.50798016 2.47562538 5.04047064]] [[-0.0002949  -0.00085585 -0.00060451 -0.00100046]]
(1, 4) (1, 4)
[[2.51943371 2.50897406 2.47616048 5.0414712 ]] [[-0.00013126 -0.0009939  -0.0005351  -0.00100056]]
(1, 4) (1, 4)
[[2.51985491 2.50937157 2.47663994 5.04247236]] [[-0.00042121 -0.00039751 -0.00047946 -0.00100116]]
(1, 4) (1, 4)
[[2.51985527 2.50937217 2.47664028 5.04247327]] [[-3.50479600e-07 -5.97678534e-07 -3.39088388e-07 -9.09788211e-07]]
(1, 4) (1, 4)
[[2.5198556  2.50937258 

[[2.57142648 2.5548397  2.52896698 5.1417159 ]] [[-0.00082146 -0.00013572 -0.00059983 -0.00100011]]
(1, 4) (1, 4)
[[2.57167066 2.55519005 2.52960322 5.14271616]] [[-0.00024418 -0.00035035 -0.00063624 -0.00100026]]
(1, 4) (1, 4)
[[2.57218843 2.55521823 2.53047602 5.14371633]] [[-5.17768609e-04 -2.81797548e-05 -8.72801145e-04 -1.00016208e-03]]
(1, 4) (1, 4)
[[2.57218844 2.55521825 2.53047604 5.14371635]] [[-1.29673499e-08 -2.19524170e-08 -2.02034927e-08 -2.57690926e-08]]
(1, 4) (1, 4)
[[2.57293354 2.55539028 2.53138091 5.14471641]] [[-0.00074509 -0.00017203 -0.00090487 -0.00100006]]
(1, 4) (1, 4)
[[2.57340908 2.55574831 2.53232451 5.14571647]] [[-0.00047555 -0.00035804 -0.00094359 -0.00100007]]
(1, 4) (1, 4)
[[2.57340913 2.55574837 2.53232454 5.14571655]] [[-4.37875618e-08 -5.07392618e-08 -3.51045255e-08 -7.56944836e-08]]
(1, 4) (1, 4)
[[2.57436132 2.55638635 2.53232845 5.14671665]] [[-9.52194215e-04 -6.37984008e-04 -3.90807732e-06 -1.00010062e-03]]
(1, 4) (1, 4)
[[2.57436138 2.55638641 

[[2.6357989  2.61598972 2.58454762 5.26578575]] [[-6.84326496e-08 -2.44188908e-07 -3.51220707e-08 -2.95638953e-07]]
(1, 4) (1, 4)
[[2.63638178 2.61678806 2.5852625  5.26678578]] [[-0.00058287 -0.00079834 -0.00071488 -0.00100003]]
(1, 4) (1, 4)
[[2.63638193 2.61678812 2.58526254 5.26678598]] [[-1.57793171e-07 -6.22386614e-08 -4.47556141e-08 -1.99214189e-07]]
(1, 4) (1, 4)
[[2.63638204 2.61678824 2.58526255 5.26678614]] [[-1.02197854e-07 -1.18089780e-07 -4.59930102e-09 -1.58691656e-07]]
(1, 4) (1, 4)
[[2.63638213 2.61678826 2.58526265 5.26678629]] [[-9.37590658e-08 -2.17156668e-08 -1.01679044e-07 -1.50206855e-07]]
(1, 4) (1, 4)
[[2.63638215 2.61678828 2.58526266 5.26678631]] [[-1.55031509e-08 -1.91187499e-08 -9.97437316e-09 -1.99544757e-08]]
(1, 4) (1, 4)
[[2.63638227 2.61678835 2.5852627  5.26678648]] [[-1.21642379e-07 -6.87807142e-08 -4.64391243e-08 -1.70166913e-07]]
(1, 4) (1, 4)
[[2.63721947 2.61679232 2.58624577 5.26778653]] [[-8.37203155e-04 -3.96812207e-06 -9.83071292e-04 -1.00005

(1, 4) (1, 4)
[[2.70672982 2.69266532 2.66467661 5.41887059]] [[-2.88196016e-08 -1.61011618e-07 -7.70947291e-08 -2.00363811e-07]]
(1, 4) (1, 4)
[[2.70672985 2.69266533 2.66467663 5.41887062]] [[-3.04171272e-08 -1.27323416e-08 -2.36998900e-08 -3.27327616e-08]]
(1, 4) (1, 4)
[[2.70752747 2.69321528 2.66483952 5.41987074]] [[-0.00079762 -0.00054995 -0.00016288 -0.00100013]]
(1, 4) (1, 4)
[[2.70845696 2.69337756 2.66491223 5.42087105]] [[-9.29489203e-04 -1.62274348e-04 -7.27132125e-05 -1.00030154e-03]]
(1, 4) (1, 4)
[[2.70923588 2.69394907 2.66580977 5.42187107]] [[-0.00077892 -0.00057151 -0.00089754 -0.00100002]]
(1, 4) (1, 4)
[[2.70923604 2.69394909 2.66580993 5.42187134]] [[-1.51015765e-07 -2.47571599e-08 -1.59965408e-07 -2.79439461e-07]]
(1, 4) (1, 4)
[[2.70952497 2.69430976 2.6662145  5.42287175]] [[-0.00028894 -0.00036066 -0.00040457 -0.00100041]]
(1, 4) (1, 4)
[[2.709525   2.69430982 2.66621453 5.42287181]] [[-2.21203376e-08 -6.13780337e-08 -2.83246728e-08 -6.25147021e-08]]
(1, 4) (

[[2.77809795 2.76143888 2.72474429 5.55594988]] [[-1.49171816e-08 -2.58055167e-08 -1.44877260e-08 -2.58603454e-08]]
(1, 4) (1, 4)
[[2.77809817 2.76143927 2.72474444 5.55595108]] [[-2.14935622e-07 -3.87639679e-07 -1.48610293e-07 -1.19664036e-06]]
(1, 4) (1, 4)
[[2.77840996 2.76221518 2.72478753 5.55695141]] [[-3.11790059e-04 -7.75911996e-04 -4.30909505e-05 -1.00033120e-03]]
(1, 4) (1, 4)
[[2.77892619 2.76248623 2.72566152 5.55795149]] [[-0.00051623 -0.00027105 -0.00087399 -0.00100009]]
(1, 4) (1, 4)
[[2.77917938 2.76302868 2.72663523 5.55895156]] [[-0.0002532  -0.00054245 -0.00097371 -0.00100007]]
(1, 4) (1, 4)
[[2.77917953 2.76302871 2.72663536 5.55895182]] [[-1.51123792e-07 -3.23075019e-08 -1.32005229e-07 -2.55149799e-07]]
(1, 4) (1, 4)
[[2.77956164 2.76384581 2.7270179  5.55995192]] [[-0.0003821  -0.0008171  -0.00038254 -0.00100011]]
(1, 4) (1, 4)
[[2.779654   2.76452213 2.72765044 5.56095209]] [[-9.23639708e-05 -6.76315633e-04 -6.32540768e-04 -1.00016941e-03]]
(1, 4) (1, 4)
[[2.7796

[[2.84812635 2.82774292 2.79624751 5.69601328]] [[-0.00026979 -0.00060615 -0.000276   -0.00100032]]
(1, 4) (1, 4)
[[2.84896027 2.8278111  2.796814   5.69701342]] [[-8.33912010e-04 -6.81787529e-05 -5.66483916e-04 -1.00014093e-03]]
(1, 4) (1, 4)
[[2.84896037 2.82781113 2.79681405 5.69701354]] [[-9.95907123e-08 -2.92943522e-08 -5.75144384e-08 -1.22411585e-07]]
(1, 4) (1, 4)
[[2.84896038 2.82781114 2.79681406 5.69701356]] [[-1.39604783e-08 -1.57429497e-08 -7.40580546e-09 -1.59892458e-08]]
(1, 4) (1, 4)
[[2.84896047 2.82781138 2.79681407 5.69701385]] [[-9.37793995e-08 -2.39026709e-07 -1.22877904e-08 -2.92755270e-07]]
(1, 4) (1, 4)
[[2.84896074 2.82781172 2.79681411 5.69701467]] [[-2.63817292e-07 -3.34491241e-07 -3.81455789e-08 -8.23448870e-07]]
(1, 4) (1, 4)
[[2.84965593 2.82809401 2.79756301 5.69801475]] [[-0.0006952  -0.00028229 -0.00074889 -0.00100007]]
(1, 4) (1, 4)
[[2.85011438 2.82817198 2.7981936  5.69901505]] [[-4.58446308e-04 -7.79732547e-05 -6.30597284e-04 -1.00030620e-03]]
(1, 4)

[[2.92302969 2.9029602  2.87212416 5.8490957 ]] [[-1.34829250e-07 -1.56713913e-07 -1.32753828e-08 -2.44042656e-07]]
(1, 4) (1, 4)
[[2.9230297  2.90296048 2.87212422 5.849096  ]] [[-8.59047625e-09 -2.82264225e-07 -6.26718273e-08 -3.02255212e-07]]
(1, 4) (1, 4)
[[2.92389682 2.90317512 2.87228811 5.85009625]] [[-0.00086713 -0.00021464 -0.00016389 -0.00100025]]
(1, 4) (1, 4)
[[2.92389698 2.90317519 2.87228813 5.85009642]] [[-1.55139390e-07 -6.36150538e-08 -1.75290747e-08 -1.70082037e-07]]
(1, 4) (1, 4)
[[2.9248677  2.90379298 2.87273402 5.85109645]] [[-0.00097072 -0.00061779 -0.00044589 -0.00100003]]
(1, 4) (1, 4)
[[2.92577603 2.90426653 2.87328315 5.85209649]] [[-0.00090833 -0.00047355 -0.00054914 -0.00100004]]
(1, 4) (1, 4)
[[2.92577603 2.90426661 2.87328328 5.85209663]] [[-2.80856521e-09 -8.32444095e-08 -1.20406349e-07 -1.39492962e-07]]
(1, 4) (1, 4)
[[2.92596286 2.90496743 2.87387111 5.85309677]] [[-0.00018683 -0.00070082 -0.00058783 -0.00100014]]
(1, 4) (1, 4)
[[2.92596287 2.90496759 

KeyboardInterrupt: 