In [4]:
import numpy as np
import time

def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-1]
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y.reshape(-1,1)
    
n, dimension, train_x, train_y = read_data('classification.txt')
# train_y = (train_y+1.0)/2
train_x, np.squeeze(train_y)

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]),
 array([ 1., -1.,  1., ...,  1.,  1.,  1.]))

In [5]:
pos_zero_threshold = 1e-7
neg_zero_threshold = -1e-7

def activate(val, threshold = neg_zero_threshold):
    activation_func = np.vectorize(lambda x: 1.0 if x > threshold else -1.0)
    return activation_func(val)

def predict(n, train_x, train_y, W):
#     output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
#     return np.array(output).reshape(-1,1)
    return activate(np.dot(train_x, W.reshape(-1,1))*train_y)

def get_accuracy(n, hypothesis, train_y):
    return (np.abs(hypothesis-train_y)<pos_zero_threshold).sum().astype('float')/n

def perceptron(n, dimension, train_x, train_y, max_epoch, learning_rate):
#     weight=np.ones((1,dimension))*-1.0
    weight = np.array([-1.0]*dimension)

    for epoch in range(max_epoch):
        hypothesis=predict(n, train_x, train_y, weight)#-train_y
#         print [activation(np.sum(train_x[i,:]*weight)*train_y[i,:]) for i in range(n)],'=?=', activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

#         error = activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

        accuracy = get_accuracy(n, hypothesis, train_y)
        
        delta = (hypothesis-train_y)*learning_rate*train_x
#         print 'Epoch #%d: accuracy_rate=%.2f'%(epoch+1,accuracy)#,(np.abs(error+train_y)<pos_zero_threshold).sum(),weight
        
        if (np.abs(hypothesis-train_y)<pos_zero_threshold).sum()==n:
            break

#         print delta.T, train_y, np.squeeze(np.dot(delta.T,train_y).T),weight
#         weight-=np.dot(delta.T,train_y).T
        weight-=np.squeeze(np.dot(delta.T,train_y).T)

    return weight, accuracy, hypothesis, epoch

start_time = time.time()
weight, accuracy, prediction, epoch = perceptron(n, dimension, train_x, train_y, max_epoch=5000, learning_rate=1e-6)
print 'After %d epoch(s), %.3f s elapsed:'% (epoch, time.time()-start_time)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f' % accuracy

After 2699 epoch(s), 0.949 s elapsed:
Weight matrix = [-0.1920512  -0.18236201 -0.19212661  0.54228   ]
Accuracy rate=1.00


In [6]:
# After 2541 epoch(s), 0.859 s elapsed:
# Weight matrix = [-0.00058477 -0.00057694 -0.00068078  0.00235   ]
# Accuracy rate=1.00

In [7]:
prediction=predict(n, train_x, train_y, weight)
print prediction.T, (prediction==train_y).sum()

[[ 1. -1.  1. ...  1.  1.  1.]] 2000


In [3]:
print (prediction).T, np.sign(prediction).T
print (np.sign(prediction)-train_y).T, ((np.sign(prediction)-train_y)<pos_zero_threshold).sum()

[[ 1. -1.  1. ...  1.  1.  1.]] [[ 1. -1.  1. ...  1.  1.  1.]]
[[0. 0. 0. ... 0. 0. 0.]] 2000


In [8]:
pos_zero_threshold = 1e-7
neg_zero_threshold = -1e-7

def sigmoid(val):
    if val>20:
        return 1
    if val<-1000:
        return 0
    return 1.0/(1.0+np.exp(-val))

def activate(val, threshold = neg_zero_threshold):
#     activation_func = np.vectorize(lambda x: 1.0 if x > threshold else -1.0)
    activation_func = np.vectorize(lambda x: sigmoid(x)*2.0-1.0)
#     activation_func = np.vectorize(lambda x: sigmoid(x))
    return activation_func(val)

def predict(n, train_x, train_y, W):
#     output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
#     return np.array(output).reshape(-1,1)
    return activate(np.dot(train_x, W.reshape(-1,1))*train_y)

def get_accuracy(n, hypothesis, train_y):
    return ((np.sign(prediction)-train_y)<pos_zero_threshold).sum().astype('float')/n

def logistic(n, dimension, train_x, train_y, max_epoch, learning_rate):
#     weight=np.ones((1,dimension))*-1.0
    weight = np.array([-1.0]*dimension)

    for epoch in range(max_epoch):
        hypothesis=predict(n, train_x, train_y, weight)#-train_y
        
#         print train_x.shape, train_y.shape, weight.shape
#         print [activation(np.sum(train_x[i,:]*weight)*train_y[i,:]) for i in range(n)],'=?=', activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

#         error = activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

        accuracy = get_accuracy(n, hypothesis, train_y)
        
#         print hypothesis.shape, train_x.shape
#         break
        delta = (hypothesis-train_y)*learning_rate*train_x/n
        print 'Epoch #%d: accuracy_rate=%.2f'%(epoch+1,accuracy),((np.sign(prediction)-train_y)<pos_zero_threshold).sum(),weight,hypothesis.T,delta
        
#         if ((np.sign(prediction)-train_y)<pos_zero_threshold).sum()==n:
#             break

#         print delta.T, train_y, np.squeeze(np.dot(delta.T,train_y).T),weight
#         weight-=np.dot(delta.T,train_y).T
        weight-=np.squeeze(np.dot(delta.T,train_y).T)

    return weight, accuracy, hypothesis, epoch

start_time = time.time()
weight, accuracy, prediction, epoch = logistic(n, dimension, train_x, train_y, max_epoch=1000, learning_rate=1e-4)
print 'After %d epoch(s), %.3f s elapsed:'% (epoch, time.time()-start_time)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f' % accuracy

Epoch #1: accuracy_rate=1.00 2000 [-1. -1. -1. -1.] [[-0.94748205  0.83424475 -0.94647541 ... -0.68628679 -0.83101858
  -0.85853774]] [[-7.30375874e-08 -9.51742211e-08 -8.62401061e-08 -9.73741023e-08]
 [ 8.05154293e-08  1.76555308e-09  4.64716111e-08  9.17122377e-08]
 [-7.56521614e-08 -9.67462478e-08 -8.00238715e-08 -9.73237706e-08]
 ...
 [-4.34645818e-08 -1.29459309e-08 -1.07542483e-09 -8.43143394e-08]
 [-2.08943296e-08 -8.89466322e-08 -1.67592274e-08 -9.15509291e-08]
 [-3.38175002e-08 -4.57265900e-08 -6.68633665e-08 -9.29268870e-08]]
Epoch #2: accuracy_rate=1.00 2000 [-0.99990799 -0.99990672 -0.99990797 -0.99981675] [[-0.94746031  0.83419725 -0.94645336 ... -0.68622167 -0.83097035
  -0.8584945 ]] [[-7.30367723e-08 -9.51731589e-08 -8.62391436e-08 -9.73730155e-08]
 [ 8.05133440e-08  1.76550735e-09  4.64704075e-08  9.17098625e-08]
 [-7.56513045e-08 -9.67451519e-08 -8.00229650e-08 -9.73226682e-08]
 ...
 [-4.34629033e-08 -1.29454309e-08 -1.07538330e-09 -8.43110833e-08]
 [-2.08937792e-08 -

Epoch #53: accuracy_rate=1.00 2000 [-0.99521839 -0.99515212 -0.99521713 -0.9904769 ] [[-0.9463408   0.83175954 -0.94531781 ... -0.68288799 -0.82849546
  -0.85627459]] [[-7.29947867e-08 -9.51184480e-08 -8.61895685e-08 -9.73170401e-08]
 [ 8.04063391e-08  1.76316093e-09  4.64086468e-08  9.15879770e-08]
 [-7.56071699e-08 -9.66887113e-08 -7.99762800e-08 -9.72658907e-08]
 ...
 [-4.33769767e-08 -1.29198377e-08 -1.07325726e-09 -8.41443994e-08]
 [-2.08655375e-08 -8.88240649e-08 -1.67361334e-08 -9.14247731e-08]
 [-3.37763204e-08 -4.56709084e-08 -6.67819465e-08 -9.28137294e-08]]
Epoch #54: accuracy_rate=1.00 2000 [-0.99512649 -0.99505895 -0.9951252  -0.99029389] [[-0.94631863  0.83171145 -0.94529533 ... -0.68282238 -0.82844664
  -0.85623077]] [[-7.29939553e-08 -9.51173647e-08 -8.61885868e-08 -9.73159317e-08]
 [ 8.04042281e-08  1.76311464e-09  4.64074284e-08  9.15855725e-08]
 [-7.56062960e-08 -9.66875938e-08 -7.99753557e-08 -9.72647665e-08]
 ...
 [-4.33752855e-08 -1.29193340e-08 -1.07321541e-09 -8

Epoch #105: accuracy_rate=1.00 2000 [-0.99044243 -0.99030998 -0.99043993 -0.98096629] [[-0.94517691  0.82924373 -0.94413738 ... -0.67946377 -0.82594149
  -0.85398098]] [[-7.29511367e-08 -9.50615684e-08 -8.61380282e-08 -9.72588457e-08]
 [ 8.02959057e-08  1.76073933e-09  4.63449072e-08  9.14621863e-08]
 [-7.55612908e-08 -9.66300397e-08 -7.99277497e-08 -9.72068689e-08]
 ...
 [-4.32887163e-08 -1.28935493e-08 -1.07107347e-09 -8.39731883e-08]
 [-2.08363933e-08 -8.86999988e-08 -1.67127570e-08 -9.12970744e-08]
 [-3.37345864e-08 -4.56144775e-08 -6.66994308e-08 -9.26990488e-08]]
Epoch #106: accuracy_rate=1.00 2000 [-0.99035065 -0.99021692 -0.99034811 -0.98078351] [[-0.94515431  0.82919504 -0.94411445 ... -0.67939767 -0.82589207
  -0.85393657]] [[-7.29502889e-08 -9.50604636e-08 -8.61370271e-08 -9.72577154e-08]
 [ 8.02937688e-08  1.76069248e-09  4.63436739e-08  9.14597522e-08]
 [-7.55603997e-08 -9.66289002e-08 -7.99268071e-08 -9.72057225e-08]
 ...
 [-4.32870125e-08 -1.28930418e-08 -1.07103131e-09 

Epoch #156: accuracy_rate=1.00 2000 [-0.98576389 -0.98556661 -0.98576019 -0.97165084] [[-0.94401306  0.82674639 -0.9429571  ... -0.67608076 -0.82340649
  -0.85170166]] [[-7.29074880e-08 -9.50046905e-08 -8.60864895e-08 -9.72006531e-08]
 [ 8.01862834e-08  1.75833552e-09  4.62816358e-08  9.13373195e-08]
 [-7.55154180e-08 -9.65713763e-08 -7.98792261e-08 -9.71478552e-08]
 ...
 [-4.32015182e-08 -1.28675773e-08 -1.06891597e-09 -8.38040380e-08]
 [-2.08074656e-08 -8.85768544e-08 -1.66895543e-08 -9.11703244e-08]
 [-3.36931126e-08 -4.55583983e-08 -6.66174294e-08 -9.25850830e-08]]
Epoch #157: accuracy_rate=1.00 2000 [-0.98567221 -0.98547366 -0.98566848 -0.9714683 ] [[-0.94399002  0.82669713 -0.94293374 ... -0.67601418 -0.82335648
  -0.85165667]] [[-7.29066238e-08 -9.50035643e-08 -8.60854690e-08 -9.71995009e-08]
 [ 8.01841209e-08  1.75828810e-09  4.62803877e-08  9.13348563e-08]
 [-7.55145098e-08 -9.65702148e-08 -7.98782654e-08 -9.71466868e-08]
 ...
 [-4.31998022e-08 -1.28670662e-08 -1.06887351e-09 

Epoch #208: accuracy_rate=1.00 2000 [-0.98099936 -0.98073606 -0.98099445 -0.96216539] [[-0.94280324  0.82416942 -0.94173034 ... -0.67260637 -0.82079087
  -0.84934703]] [[-7.28621153e-08 -9.49455659e-08 -8.60329150e-08 -9.71401619e-08]
 [ 8.00731655e-08  1.75585506e-09  4.62163468e-08  9.12084709e-08]
 [-7.54677385e-08 -9.65104023e-08 -7.98287913e-08 -9.70865172e-08]
 ...
 [-4.31119646e-08 -1.28409038e-08 -1.06670018e-09 -8.36303183e-08]
 [-2.07776180e-08 -8.84497939e-08 -1.66656137e-08 -9.10395436e-08]
 [-3.36502682e-08 -4.55004659e-08 -6.65327183e-08 -9.24673513e-08]]
Epoch #209: accuracy_rate=1.00 2000 [-0.98090779 -0.98064323 -0.98090286 -0.9619831 ] [[-0.94277974  0.82411956 -0.94170652 ... -0.6725393  -0.82074027
  -0.84930144]] [[-7.28612340e-08 -9.49444175e-08 -8.60318745e-08 -9.71389870e-08]
 [ 8.00709768e-08  1.75580706e-09  4.62150836e-08  9.12059778e-08]
 [-7.54668125e-08 -9.65092181e-08 -7.98278118e-08 -9.70853260e-08]
 ...
 [-4.31102360e-08 -1.28403889e-08 -1.06665741e-09 

Epoch #255: accuracy_rate=1.00 2000 [-0.97669802 -0.97637512 -0.97669204 -0.95360313] [[-0.94168932  0.82181345 -0.94060096 ... -0.66944434 -0.81839976
  -0.847192  ]] [[-7.28203394e-08 -9.48911284e-08 -8.59835876e-08 -9.70844661e-08]
 [ 7.99697484e-08  1.75358731e-09  4.61566569e-08  9.10906723e-08]
 [-7.54238434e-08 -9.64542679e-08 -7.97823596e-08 -9.70300478e-08]
 ...
 [-4.30304623e-08 -1.28166283e-08 -1.06468361e-09 -8.34722170e-08]
 [-2.07503323e-08 -8.83336393e-08 -1.66437280e-08 -9.09199882e-08]
 [-3.36110559e-08 -4.54474448e-08 -6.64551885e-08 -9.23596001e-08]]
Epoch #256: accuracy_rate=1.00 2000 [-0.97660655 -0.97628239 -0.97660055 -0.95342107] [[-0.94166541  0.82176304 -0.94057671 ... -0.66937684 -0.81834861
  -0.84714587]] [[-7.28194426e-08 -9.48899597e-08 -8.59825287e-08 -9.70832704e-08]
 [ 7.99675359e-08  1.75353880e-09  4.61553799e-08  9.10881520e-08]
 [-7.54229011e-08 -9.64530629e-08 -7.97813629e-08 -9.70288356e-08]
 ...
 [-4.30287225e-08 -1.28161101e-08 -1.06464056e-09 

Epoch #299: accuracy_rate=1.00 2000 [-0.97267563 -0.97229701 -0.97266867 -0.94559707] [[-0.94062868  0.81958468 -0.93952568 ... -0.66646552 -0.81613794
  -0.84515132]] [[-7.27805615e-08 -9.48392944e-08 -8.59366193e-08 -9.70314340e-08]
 [ 7.98719155e-08  1.75144202e-09  4.61001901e-08  9.09792342e-08]
 [-7.53820516e-08 -9.64008233e-08 -7.97381528e-08 -9.69762841e-08]
 ...
 [-4.29536822e-08 -1.27937594e-08 -1.06278387e-09 -8.33232759e-08]
 [-2.07245219e-08 -8.82237650e-08 -1.66230256e-08 -9.08068968e-08]
 [-3.35739242e-08 -4.53972368e-08 -6.63817723e-08 -9.22575661e-08]]
Epoch #300: accuracy_rate=1.00 2000 [-0.97258426 -0.97220438 -0.97257728 -0.94541523] [[-0.94060437  0.81953377 -0.93950104 ... -0.66639761 -0.81608627
  -0.84510468]] [[-7.27796499e-08 -9.48381064e-08 -8.59355429e-08 -9.70302186e-08]
 [ 7.98696805e-08  1.75139301e-09  4.60989001e-08  9.09766885e-08]
 [-7.53810939e-08 -9.63995985e-08 -7.97371398e-08 -9.69750520e-08]
 ...
 [-4.29519319e-08 -1.27932380e-08 -1.06274056e-09 

Epoch #351: accuracy_rate=1.00 2000 [-0.96792745 -0.96748306 -0.96791935 -0.93614756] [[-0.93935265  0.81692167 -0.93823218 ... -0.66292194 -0.81343562
  -0.84271048]] [[-7.27327057e-08 -9.47769341e-08 -8.58801129e-08 -9.69676323e-08]
 [ 7.97550205e-08  1.74887873e-09  4.60327210e-08  9.08460834e-08]
 [-7.53317781e-08 -9.63365320e-08 -7.96849741e-08 -9.69116091e-08]
 ...
 [-4.28623453e-08 -1.27665547e-08 -1.06052396e-09 -8.31460969e-08]
 [-2.06936849e-08 -8.80924929e-08 -1.65982914e-08 -9.06717811e-08]
 [-3.35295113e-08 -4.53371836e-08 -6.62939598e-08 -9.21355242e-08]]
Epoch #352: accuracy_rate=1.00 2000 [-0.9678362  -0.96739055 -0.96782807 -0.93596597] [[-0.93932787  0.81687015 -0.93820706 ... -0.66285355 -0.81338334
  -0.84266323]] [[-7.27317763e-08 -9.47757231e-08 -8.58790156e-08 -9.69663933e-08]
 [ 7.97527589e-08  1.74882914e-09  4.60314157e-08  9.08435073e-08]
 [-7.53308018e-08 -9.63352835e-08 -7.96839415e-08 -9.69103531e-08]
 ...
 [-4.28605825e-08 -1.27660296e-08 -1.06048035e-09 

Epoch #394: accuracy_rate=1.00 2000 [-0.96400567 -0.96350696 -0.96399664 -0.92834362] [[-0.93827876  0.81469569 -0.9371437  ... -0.65997278 -0.81117698
  -0.84066812]] [[-7.26924311e-08 -9.47244529e-08 -8.58325581e-08 -9.69139380e-08]
 [ 7.96573099e-08  1.74673612e-09  4.59763248e-08  9.07347847e-08]
 [-7.52894730e-08 -9.62824311e-08 -7.96402244e-08 -9.68571851e-08]
 ...
 [-4.27863299e-08 -1.27439135e-08 -1.05864315e-09 -8.29986390e-08]
 [-2.06679109e-08 -8.79827734e-08 -1.65776182e-08 -9.05588491e-08]
 [-3.34923489e-08 -4.52869341e-08 -6.62204830e-08 -9.20334058e-08]]
Epoch #395: accuracy_rate=1.00 2000 [-0.96391452 -0.96341454 -0.96390546 -0.92816224] [[-0.93825358  0.81464367 -0.93711818 ... -0.65990399 -0.8111242
  -0.84062036]] [[-7.26914868e-08 -9.47232224e-08 -8.58314432e-08 -9.69126791e-08]
 [ 7.96550262e-08  1.74668604e-09  4.59750067e-08  9.07321835e-08]
 [-7.52884812e-08 -9.62811627e-08 -7.96391753e-08 -9.68559092e-08]
 ...
 [-4.27845568e-08 -1.27433854e-08 -1.05859928e-09 -

Epoch #445: accuracy_rate=1.00 2000 [-0.95935972 -0.95879666 -0.9593496  -0.91909975] [[-0.93698281  0.81202745 -0.93583028 ... -0.65645286 -0.80846979
  -0.83821745]] [[-7.26438283e-08 -9.46611193e-08 -8.57751698e-08 -9.68491406e-08]
 [ 7.95401855e-08  1.74416780e-09  4.59087233e-08  9.06013725e-08]
 [-7.52384251e-08 -9.62171494e-08 -7.95862266e-08 -9.67915138e-08]
 ...
 [-4.26956027e-08 -1.27168903e-08 -1.05639832e-09 -8.28226428e-08]
 [-2.06370183e-08 -8.78512645e-08 -1.65528394e-08 -9.04234897e-08]
 [-3.34477572e-08 -4.52266391e-08 -6.61323171e-08 -9.19108726e-08]]
Epoch #446: accuracy_rate=1.00 2000 [-0.95926868 -0.95870436 -0.95925854 -0.91891863] [[-0.93695716  0.81197483 -0.93580428 ... -0.6563836  -0.8084164
  -0.83816909]] [[-7.26428662e-08 -9.46598656e-08 -8.57740337e-08 -9.68478578e-08]
 [ 7.95378755e-08  1.74411715e-09  4.59073900e-08  9.05987413e-08]
 [-7.52374146e-08 -9.62158572e-08 -7.95851577e-08 -9.67902138e-08]
 ...
 [-4.26938175e-08 -1.27163586e-08 -1.05635415e-09 -

Epoch #485: accuracy_rate=1.00 2000 [-0.95572002 -0.95510655 -0.95570906 -0.91185882] [[-0.93594925  0.80991326 -0.93478288 ... -0.65367541 -0.80632491
  -0.83627374]] [[-7.26050660e-08 -9.46106087e-08 -8.57294007e-08 -9.67974625e-08]
 [ 7.94473816e-08  1.74213278e-09  4.58551591e-08  9.04956629e-08]
 [-7.51977166e-08 -9.61650902e-08 -7.95431657e-08 -9.67391438e-08]
 ...
 [-4.26240133e-08 -1.26955674e-08 -1.05462702e-09 -8.26837707e-08]
 [-2.06125423e-08 -8.77470709e-08 -1.65332074e-08 -9.03162454e-08]
 [-3.34123898e-08 -4.51788169e-08 -6.60623893e-08 -9.18136868e-08]]
Epoch #486: accuracy_rate=1.00 2000 [-0.95562908 -0.95501435 -0.9556181  -0.9116779 ] [[-0.93592322  0.80986016 -0.9347565  ... -0.65360579 -0.80627104
  -0.8362249 ]] [[-7.26040897e-08 -9.46093365e-08 -8.57282478e-08 -9.67961608e-08]
 [ 7.94450508e-08  1.74208168e-09  4.58538138e-08  9.04930080e-08]
 [-7.51966913e-08 -9.61637790e-08 -7.95420811e-08 -9.67378248e-08]
 ...
 [-4.26222187e-08 -1.26950329e-08 -1.05458261e-09 

Epoch #523: accuracy_rate=1.00 2000 [-0.95226576 -0.95160445 -0.95225401 -0.90498748] [[-0.93495324  0.80788724 -0.93377362 ... -0.65102328 -0.80426961
  -0.8344095 ]] [[-7.25677121e-08 -9.45619334e-08 -8.56852945e-08 -9.67476620e-08]
 [ 7.93584481e-08  1.74018264e-09  4.58038288e-08  9.03943620e-08]
 [-7.51584905e-08 -9.61149266e-08 -7.95016728e-08 -9.66886808e-08]
 ...
 [-4.25556537e-08 -1.26752065e-08 -1.05293563e-09 -8.25511642e-08]
 [-2.05890887e-08 -8.76472294e-08 -1.65143954e-08 -9.02134806e-08]
 [-3.33784687e-08 -4.51329502e-08 -6.59953211e-08 -9.17204752e-08]]
Epoch #524: accuracy_rate=1.00 2000 [-0.9521749  -0.95151234 -0.95216314 -0.90480676] [[-0.93492684  0.80783369 -0.93374687 ... -0.65095331 -0.80421529
  -0.83436021]] [[-7.25667221e-08 -9.45606433e-08 -8.56841256e-08 -9.67463421e-08]
 [ 7.93560976e-08  1.74013110e-09  4.58024721e-08  9.03916846e-08]
 [-7.51574509e-08 -9.61135972e-08 -7.95005731e-08 -9.66873434e-08]
 ...
 [-4.25538502e-08 -1.26746694e-08 -1.05289100e-09 

Epoch #572: accuracy_rate=1.00 2000 [-0.94781659 -0.94709367 -0.94780385 -0.89613801] [[-0.93364835  0.80524943 -0.93245149 ... -0.64758399 -0.80159388
  -0.83198004]] [[-7.25187740e-08 -9.44981628e-08 -8.56275102e-08 -9.66824174e-08]
 [ 7.92426596e-08  1.73764361e-09  4.57369984e-08  9.02624714e-08]
 [-7.51071043e-08 -9.60492125e-08 -7.94473171e-08 -9.66225744e-08]
 ...
 [-4.24670049e-08 -1.26488025e-08 -1.05074223e-09 -8.23791996e-08]
 [-2.05585551e-08 -8.75172486e-08 -1.64899045e-08 -9.00796941e-08]
 [-3.33342627e-08 -4.50731767e-08 -6.59079177e-08 -9.15990018e-08]]
Epoch #573: accuracy_rate=1.00 2000 [-0.94772585 -0.94700168 -0.94771309 -0.89595754] [[-0.93362147  0.8051953  -0.93242426 ... -0.64751358 -0.80153898
  -0.83193015]] [[-7.25177661e-08 -9.44968495e-08 -8.56263201e-08 -9.66810737e-08]
 [ 7.92402835e-08  1.73759151e-09  4.57356269e-08  9.02597649e-08]
 [-7.51060461e-08 -9.60478592e-08 -7.94461978e-08 -9.66212130e-08]
 ...
 [-4.24651899e-08 -1.26482619e-08 -1.05069732e-09 

Epoch #624: accuracy_rate=1.00 2000 [-0.94310125 -0.94231305 -0.94308748 -0.88676036] [[-0.93223789  0.80241881 -0.93102255 ... -0.64391029 -0.79872282
  -0.82937012]] [[-7.24658768e-08 -9.44292332e-08 -8.55650511e-08 -9.66118946e-08]
 [ 7.91184078e-08  1.73491900e-09  4.56652832e-08  9.01209407e-08]
 [-7.50515670e-08 -9.59781897e-08 -7.93885705e-08 -9.65511277e-08]
 ...
 [-4.23723139e-08 -1.26205988e-08 -1.04839933e-09 -8.21955143e-08]
 [-2.05257925e-08 -8.73777791e-08 -1.64636258e-08 -8.99361410e-08]
 [-3.32867734e-08 -4.50089636e-08 -6.58140227e-08 -9.14685062e-08]]
Epoch #625: accuracy_rate=1.00 2000 [-0.94301064 -0.94222118 -0.94299684 -0.88658015] [[-0.93221051  0.80236406 -0.93099481 ... -0.6438394  -0.79866729
  -0.82931961]] [[-7.24648497e-08 -9.44278949e-08 -8.55638384e-08 -9.66105253e-08]
 [ 7.91160044e-08  1.73486630e-09  4.56638960e-08  9.01182031e-08]
 [-7.50504888e-08 -9.59768108e-08 -7.93874300e-08 -9.65497405e-08]
 ...
 [-4.23704868e-08 -1.26200545e-08 -1.04835412e-09 

Epoch #675: accuracy_rate=1.00 2000 [-0.93848292 -0.93763078 -0.93846815 -0.87757681] [[-0.93082851  0.79961119 -0.92959487 ... -0.64028349 -0.79587534
  -0.82677852]] [[-7.24130200e-08 -9.43603563e-08 -8.55026397e-08 -9.65414256e-08]
 [ 7.89951654e-08  1.73221653e-09  4.55941505e-08  8.99805597e-08]
 [-7.49960782e-08 -9.59072290e-08 -7.93298752e-08 -9.64797434e-08]
 ...
 [-4.22788321e-08 -1.25927552e-08 -1.04608635e-09 -8.20141746e-08]
 [-2.04932990e-08 -8.72394549e-08 -1.64375629e-08 -8.97937668e-08]
 [-3.32396171e-08 -4.49452009e-08 -6.57207861e-08 -9.13389258e-08]]
Epoch #676: accuracy_rate=1.00 2000 [-0.93839243 -0.93753903 -0.93837764 -0.87739688] [[-0.93080062  0.79955583 -0.92956661 ... -0.64021214 -0.79581919
  -0.82672738]] [[-7.24119738e-08 -9.43589930e-08 -8.55014044e-08 -9.65400308e-08]
 [ 7.89927352e-08  1.73216324e-09  4.55927479e-08  8.99777915e-08]
 [-7.49949800e-08 -9.59058246e-08 -7.93287136e-08 -9.64783306e-08]
 ...
 [-4.22769931e-08 -1.25922074e-08 -1.04604085e-09 

Epoch #725: accuracy_rate=1.00 2000 [-0.93396128 -0.93304655 -0.93394556 -0.86858672] [[-0.92942136  0.79682828 -0.9281696  ... -0.63670511 -0.79305316
  -0.82420689]] [[-7.23602469e-08 -9.42915884e-08 -8.54403272e-08 -9.64710682e-08]
 [ 7.88730077e-08  1.72953784e-09  4.55236440e-08  8.98414142e-08]
 [-7.49406834e-08 -9.58363884e-08 -7.92712793e-08 -9.64084799e-08]
 ...
 [-4.21865981e-08 -1.25652833e-08 -1.04380425e-09 -8.18352554e-08]
 [-2.04610942e-08 -8.71023601e-08 -1.64117317e-08 -8.96526579e-08]
 [-3.31928245e-08 -4.48819299e-08 -6.56282686e-08 -9.12103446e-08]]
Epoch #726: accuracy_rate=1.00 2000 [-0.93387091 -0.93295493 -0.93385517 -0.86840706] [[-0.92939296  0.79677232 -0.92814083 ... -0.63663331 -0.7929964
  -0.82415515]] [[-7.23591817e-08 -9.42902004e-08 -8.54390695e-08 -9.64696482e-08]
 [ 7.88705510e-08  1.72948397e-09  4.55222261e-08  8.98386159e-08]
 [-7.49395653e-08 -9.58349586e-08 -7.92700966e-08 -9.64070416e-08]
 ...
 [-4.21847476e-08 -1.25647321e-08 -1.04375846e-09 -

Epoch #774: accuracy_rate=1.00 2000 [-0.92953605 -0.92856007 -0.92951941 -0.85978943] [[-0.92801762  0.79407178 -0.92674792 ... -0.6331766  -0.790258
  -0.82165693]] [[-7.23076014e-08 -9.42229869e-08 -8.53781653e-08 -9.64008810e-08]
 [ 7.87520092e-08  1.72688457e-09  4.54538065e-08  8.97035891e-08]
 [-7.48854283e-08 -9.57657265e-08 -7.92128311e-08 -9.63373962e-08]
 ...
 [-4.20956497e-08 -1.25381943e-08 -1.04155395e-09 -8.16588298e-08]
 [-2.04291978e-08 -8.69665777e-08 -1.63861477e-08 -8.95128999e-08]
 [-3.31464260e-08 -4.48191919e-08 -6.55365303e-08 -9.10828466e-08]]
Epoch #775: accuracy_rate=1.00 2000 [-0.9294458  -0.92846857 -0.92942914 -0.85961003] [[-0.92798871  0.79401523 -0.92671865 ... -0.63310436 -0.79020065
  -0.82160458]] [[-7.23065173e-08 -9.42215743e-08 -8.53768853e-08 -9.63994357e-08]
 [ 7.87495265e-08  1.72683013e-09  4.54523736e-08  8.97007613e-08]
 [-7.48842905e-08 -9.57642716e-08 -7.92116277e-08 -9.63359325e-08]
 ...
 [-4.20937878e-08 -1.25376397e-08 -1.04150788e-09 -8

Epoch #826: accuracy_rate=1.00 2000 [-0.92484643 -0.92380554 -0.92482884 -0.85046776] [[-0.92650077  0.79111474 -0.92521187 ... -0.6294087  -0.78725975
  -0.81891845]] [[-7.22507141e-08 -9.41488579e-08 -8.53109950e-08 -9.63250386e-08]
 [ 7.86222077e-08  1.72403826e-09  4.53788882e-08  8.95557370e-08]
 [-7.48257276e-08 -9.56893796e-08 -7.91496806e-08 -9.62605935e-08]
 ...
 [-4.19985309e-08 -1.25092674e-08 -1.03915099e-09 -8.14704350e-08]
 [-2.03949838e-08 -8.68209297e-08 -1.63587049e-08 -8.93629874e-08]
 [-3.30965973e-08 -4.47518156e-08 -6.54380098e-08 -9.09459226e-08]]
Epoch #827: accuracy_rate=1.00 2000 [-0.92475632 -0.92371418 -0.9247387  -0.85028864] [[-0.92647133  0.79105755 -0.92518205 ... -0.62933601 -0.78720177
  -0.81886546]] [[-7.22496098e-08 -9.41474188e-08 -8.53096910e-08 -9.63235663e-08]
 [ 7.86196974e-08  1.72398322e-09  4.53774393e-08  8.95528776e-08]
 [-7.48245687e-08 -9.56878975e-08 -7.91484547e-08 -9.62591026e-08]
 ...
 [-4.19966572e-08 -1.25087093e-08 -1.03910462e-09 

Epoch #878: accuracy_rate=1.00 2000 [-0.92016363 -0.91905794 -0.92014511 -0.84116088] [[-0.92495557  0.78812487 -0.92364728 ... -0.6256169  -0.78422849
  -0.81614644]] [[-7.21927635e-08 -9.40733433e-08 -8.52425689e-08 -9.62477785e-08]
 [ 7.84909653e-08  1.72116036e-09  4.53031381e-08  8.94062434e-08]
 [-7.47649178e-08 -9.56116142e-08 -7.90853567e-08 -9.61823638e-08]
 ...
 [-4.19007959e-08 -1.24801571e-08 -1.03673277e-09 -8.12808448e-08]
 [-2.03603931e-08 -8.66736781e-08 -1.63309599e-08 -8.92114244e-08]
 [-3.30461584e-08 -4.46836143e-08 -6.53382831e-08 -9.08073220e-08]]
Epoch #879: accuracy_rate=1.00 2000 [-0.92007365 -0.91896671 -0.9200551  -0.84098205] [[-0.92492557  0.78806705 -0.92361691 ... -0.62554374 -0.78416987
  -0.8160928 ]] [[-7.21916385e-08 -9.40718773e-08 -8.52412406e-08 -9.62462787e-08]
 [ 7.84884272e-08  1.72110471e-09  4.53016732e-08  8.94033524e-08]
 [-7.47637374e-08 -9.56101046e-08 -7.90841081e-08 -9.61808453e-08]
 ...
 [-4.18989104e-08 -1.24795955e-08 -1.03668612e-09 

Epoch #927: accuracy_rate=1.00 2000 [-0.91575731 -0.91459064 -0.91573792 -0.83240464] [[-0.92347321  0.78527736 -0.92214648 ... -0.62202211 -0.78134181
  -0.81350352]] [[-7.21371696e-08 -9.40008996e-08 -8.51769257e-08 -9.61736604e-08]
 [ 7.83659718e-08  1.71841949e-09  4.52309948e-08  8.92638678e-08]
 [-7.47065873e-08 -9.55370194e-08 -7.90236555e-08 -9.61073238e-08]
 ...
 [-4.18081391e-08 -1.24525592e-08 -1.03444021e-09 -8.11011054e-08]
 [-2.03274524e-08 -8.65334501e-08 -1.63045383e-08 -8.90670907e-08]
 [-3.29980685e-08 -4.46185892e-08 -6.52432005e-08 -9.06751760e-08]]
Epoch #928: accuracy_rate=1.00 2000 [-0.91566745 -0.91449954 -0.91564805 -0.83222608] [[-0.92344269  0.78521894 -0.92211558 ... -0.62194853 -0.7812826
  -0.81344927]] [[-7.21360249e-08 -9.39994081e-08 -8.51755741e-08 -9.61721344e-08]
 [ 7.83634075e-08  1.71836326e-09  4.52295148e-08  8.92609470e-08]
 [-7.47053864e-08 -9.55354836e-08 -7.90223852e-08 -9.61057788e-08]
 ...
 [-4.18062425e-08 -1.24519943e-08 -1.03439328e-09 -

Epoch #970: accuracy_rate=1.00 2000 [-0.91189563 -0.91067554 -0.91187551 -0.82473164] [[-0.92215106  0.78275437 -0.92080802 ... -0.61885023 -0.77878433
  -0.81115947]] [[-7.20875843e-08 -9.39362859e-08 -8.51183773e-08 -9.61075531e-08]
 [ 7.82552235e-08  1.71599098e-09  4.51670735e-08  8.91377184e-08]
 [-7.46545664e-08 -9.54704935e-08 -7.89686285e-08 -9.60404008e-08]
 ...
 [-4.17263829e-08 -1.24282081e-08 -1.03241735e-09 -8.09425114e-08]
 [-2.02982682e-08 -8.64092136e-08 -1.62811298e-08 -8.89392166e-08]
 [-3.29554167e-08 -4.45609172e-08 -6.51588701e-08 -9.05579735e-08]]
Epoch #971: accuracy_rate=1.00 2000 [-0.91180588 -0.91058455 -0.91178574 -0.82455332] [[-0.92212008  0.78269542 -0.92077665 ... -0.61877627 -0.77872459
  -0.81110468]] [[-7.20864222e-08 -9.39347715e-08 -8.51170051e-08 -9.61060038e-08]
 [ 7.82526361e-08  1.71593425e-09  4.51655801e-08  8.91347712e-08]
 [-7.46533473e-08 -9.54689345e-08 -7.89673389e-08 -9.60388324e-08]
 ...
 [-4.17244766e-08 -1.24276403e-08 -1.03237018e-09 