In [1]:
import numpy as np
import time

def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-2:-1]
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y
    
n, dimension, train_x, train_y = read_data('classification.txt')
train_x, np.squeeze(train_y)

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]),
 array([-1.,  1., -1., ...,  1., -1., -1.]))

In [2]:
pos_zero_threshold = 1e-7
neg_zero_threshold = -1e-7

def activate(val, threshold = neg_zero_threshold):
    activation_func = np.vectorize(lambda x: 1.0 if x > threshold else -1.0)
    return activation_func(val)

def predict(n, train_x, train_y, W):
#     output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
#     return np.array(output).reshape(-1,1)
    return activate(np.dot(train_x, W.reshape(-1,1))*train_y)

def get_accuracy(n, hypothesis, train_y):
    return (np.abs(hypothesis-train_y)<pos_zero_threshold).sum().astype('float')/n

def perceptron(n, dimension, train_x, train_y, max_epoch, learning_rate):
#     weight=np.ones((1,dimension))*-1.0
    weight = np.array([-1.0]*dimension)

    for epoch in range(max_epoch):
        hypothesis=predict(n, train_x, train_y, weight)#-train_y
#         print [activation(np.sum(train_x[i,:]*weight)*train_y[i,:]) for i in range(n)],'=?=', activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

#         error = activation(np.dot(train_x, weight.reshape(-1,1))*train_y)

        accuracy = get_accuracy(n, hypothesis, train_y)
        
        delta = hypothesis*learning_rate*train_x
#         print 'Epoch #%d: accuracy_rate=%.2f'%(epoch+1,accuracy)#,(np.abs(error+train_y)<pos_zero_threshold).sum(),weight
        
        if (np.abs(hypothesis-train_y)<pos_zero_threshold).sum()==n:
            break

#         print delta.T, train_y, np.squeeze(np.dot(delta.T,train_y).T),weight
#         weight-=np.dot(delta.T,train_y).T
        weight-=np.squeeze(np.dot(delta.T,train_y).T)

    return weight, accuracy, hypothesis, epoch

start_time = time.time()
weight, accuracy, prediction, epoch = perceptron(n, dimension, train_x, train_y, max_epoch=5000, learning_rate=1e-6)
print 'After %d epoch(s), %.3f s elapsed:'% (epoch, time.time()-start_time)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f' % accuracy

After 2541 epoch(s), 0.867 s elapsed:
Weight matrix = [-0.000545   -0.00054431 -0.00064126  0.002464  ]
Accuracy rate=1.00


In [3]:
# Epoch #1: accuracy_rate=67.75% [[ 0. -2.  0. ... -2.  0.  0.]]
# Epoch #2: accuracy_rate=100.00% [[0. 0. 0. ... 0. 0. 0.]]
# Weight matrix = [[0.95456624 0.42006829 0.46490911 1.29      ]]
# Accuracy rate=100.00%

In [4]:
# Weight matrix = [[-0.04264244 -0.03744909 -0.04125117  0.1162    ]]
# Accuracy rate=1.00

In [5]:
# Weight matrix = [[-0.01829778 -0.01859523 -0.0214495   0.06384   ]]
# Accuracy rate=1.00

In [6]:
print prediction.T, (prediction==train_y).sum()

[[-1.  1. -1. ...  1. -1. -1.]] 2000
