In [1]:
import numpy as np

def read_data(filename):
    input_f=open(filename, 'r')
    input_data=[]
    for line in input_f.readlines():
        input_data.append([float(val) for val in line.split(',')])
    input_data=np.array(input_data)
    train_x=input_data[:,:-2]
    train_y=input_data[:,-2:-1]
    train_x=np.concatenate((train_x, np.ones((train_x.shape[0],1))),axis=1)
    n, dimension = train_x.shape
    return n, dimension, train_x, train_y
    
n, dimension, train_x, train_y = read_data('classification.txt')
train_x, np.squeeze(train_y)

(array([[0.750072  , 0.97740794, 0.88565752, 1.        ],
        [0.87791369, 0.01925101, 0.50671112, 1.        ],
        [0.7773246 , 0.99406596, 0.82224385, 1.        ],
        ...,
        [0.5155064 , 0.15354364, 0.01275495, 1.        ],
        [0.2282263 , 0.97155357, 0.18305906, 1.        ],
        [0.36391513, 0.49207061, 0.71952659, 1.        ]]),
 array([-1.,  1., -1., ...,  1., -1., -1.]))

In [19]:
pos_zero_threshold = 1e-9
neg_zero_threshold = -1e-9

def activation(val, threshold = neg_zero_threshold):
    activation_func = np.vectorize(lambda x: 1.0 if x > threshold else -1.0)
    return activation_func(val)

def predict(n, train_x, train_y, W):
    output=[activation(np.sum(train_x[i,:]*W)*train_y[i,:]) for i in range(n)]
    return np.array(output).reshape(-1,1)

def get_accuracy(error):
#     return 1.0-np.sum([1.0 if np.sum(np.abs(x))>0.0 else 0.0 for x in error])/error.shape[0]
    return (np.abs(error-train_y)<pos_zero_threshold).sum().astype('float')/error.shape[0]

def perceptron(n, dimension, train_x, train_y, max_epoch, learning_rate):
    weight=np.ones((1,dimension))*-1

    for epoch in range(max_epoch):
        error=predict(n, train_x, train_y, weight)#-train_y

        accuracy = get_accuracy(error)
        
        delta = error*learning_rate*train_x/n

        
        print 'Epoch #%d: accuracy_rate=%.2f'%(epoch+1,accuracy),(np.abs(error-train_y)<pos_zero_threshold).sum(),np.dot(delta.T,train_y).shape, delta, np.dot(delta.T,train_y).T, weight.T
        
#         if np.sum(error**2)<1.0:
        if (np.abs(error-train_y)<pos_zero_threshold).sum()==error.shape[0]:
            break
        
#         for i in range(n):
#             weight-=np.array([delta[i,:]*train_y[i,:]])

        weight-=np.dot(delta.T,train_y).T

    return weight, accuracy, error

weight, accuracy, error = perceptron(n, dimension, train_x, activation(train_y), max_epoch=100, learning_rate=1e-3)
print 'Weight matrix =', weight
print 'Accuracy rate=%.2f' % accuracy
print predict(n, train_x, train_y, weight)

Epoch #1: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-1.]
 [-1.]
 [-1.]
 [-1.]]
Epoch #2: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -

Epoch #17: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.99207399]
 [-0.99196445]
 [-0.9920692 ]
 [-0.984     ]]
Epoch #18: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

Epoch #32: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.98464336]
 [-0.98443111]
 [-0.98463407]
 [-0.969     ]]
Epoch #33: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

Epoch #47: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.97721273]
 [-0.97689778]
 [-0.97719895]
 [-0.954     ]]
Epoch #48: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

Epoch #63: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.96928672]
 [-0.96886223]
 [-0.96926815]
 [-0.938     ]]
Epoch #64: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

Epoch #78: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.96185609]
 [-0.9613289 ]
 [-0.96183302]
 [-0.923     ]]
Epoch #79: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

Epoch #93: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000e-07]] [[-0.00049538 -0.00050222 -0.00049568 -0.001     ]] [[-0.95442546]
 [-0.95379556]
 [-0.9543979 ]
 [-0.908     ]]
Epoch #94: accuracy_rate=0.00 0 (4, 1) [[ 3.75035999e-07  4.88703972e-07  4.42828761e-07  5.00000000e-07]
 [-4.38956846e-07 -9.62550430e-09 -2.53355562e-07 -5.00000000e-07]
 [ 3.88662302e-07  4.97032982e-07  4.11121923e-07  5.00000000e-07]
 ...
 [-2.57753202e-07 -7.67718218e-08 -6.37747292e-09 -5.00000000e-07]
 [ 1.14113149e-07  4.85776786e-07  9.15295322e-08  5.00000000e-07]
 [ 1.81957565e-07  2.46035305e-07  3.59763297e-07  5.00000000

In [3]:
# Epoch #1: accuracy_rate=67.75% [[ 0. -2.  0. ... -2.  0.  0.]]
# Epoch #2: accuracy_rate=100.00% [[0. 0. 0. ... 0. 0. 0.]]
# Weight matrix = [[0.95456624 0.42006829 0.46490911 1.29      ]]
# Accuracy rate=100.00%

In [ ]:
Weight matrix = [[-0.00924906  0.00444425 -0.00864991  1.        ]]
Accuracy rate=0.00