In [41]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Read data from file
input_f = open('pca-data.txt', 'r')
data = input_f.readlines()
x = []
for record in data:
    x.append(record.split())
X = np.array(x).astype(np.float)
original_x = X.copy()
original_x

array([[  5.90626285,  -7.72946458,   9.14494487],
       [ -8.64032311,   1.72426044, -10.69680519],
       [  0.25854061,   0.23062224,   0.76743916],
       ...,
       [ -3.69142791,  -0.474338  ,   0.55020057],
       [  7.63831529,  -4.47583291,   8.15392291],
       [  9.72207756,  -8.50135442,   8.8424068 ]])

In [42]:
X = StandardScaler().fit_transform(X)

# Compute the mean of the data
mean_vec = np.mean(X, axis=0)

# Compute the covariance matrix
cov_mat = (X - mean_vec).T.dot((X - mean_vec)) / (X.shape[0]-1)


# OR we can do this with one line of numpy:
# cov_mat = np.cov(X.T)
cov_mat

array([[ 1.00016669, -0.47486543,  0.62744169],
       [-0.47486543,  1.00016669, -0.73642685],
       [ 0.62744169, -0.73642685,  1.00016669]])

In [43]:
# Compute the eigen values and vectors using numpy
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
eig_vals, eig_vecs

(array([2.23212305, 0.53656107, 0.23181596]),
 array([[ 0.53627113, -0.79599505, -0.28072256],
        [-0.57568437, -0.58816792,  0.56801937],
        [ 0.61725261,  0.1430048 ,  0.77365938]]))

In [44]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)
eig_pairs

[(2.2321230533155125, array([ 0.53627113, -0.57568437,  0.61725261])),
 (0.5365610685970897, array([-0.79599505, -0.58816792,  0.1430048 ])),
 (0.231815961434618, array([-0.28072256,  0.56801937,  0.77365938]))]

In [45]:
num_vec_to_keep = 2
# Compute the projection matrix based on the top eigen vectors
num_features = X.shape[1]
proj_mat = eig_pairs[0][1].reshape(num_features,1)
for eig_vec_idx in range(1, num_vec_to_keep):
  proj_mat = np.hstack((proj_mat, eig_pairs[eig_vec_idx][1].reshape(num_features,1)))
proj_mat

array([[ 0.53627113, -0.79599505],
       [-0.57568437, -0.58816792],
       [ 0.61725261,  0.1430048 ]])

In [46]:
# Project the data 
pca_data = X.dot(proj_mat)
print pca_data

[[ 2.54632517  0.93698904]
 [-1.97659703  0.21277546]
 [ 0.04881661 -0.04306428]
 ...
 [-0.10051112  0.41227183]
 [ 2.03409642  0.24167712]
 [ 2.86008393  0.7149131 ]]
