In [4]:
import numpy as np

grid = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

target = np.array([[0, 0],
[0, 9],
[9, 0],
[9, 9]])

noisyDist = np.array([[6.3, 5.9, 5.5, 6.7],
[5.6, 7.2, 4.4, 6.8],
[7.6, 9.4, 4.3, 5.4],
[9.5, 10.0, 3.7, 6.6],
[6.0, 10.7, 2.8, 5.8],
[9.3, 10.2, 2.6, 5.4],
[8.0, 13.1, 1.9, 9.4],
[6.4, 8.2, 3.9, 8.8],
[5.0, 10.3, 3.6, 7.2],
[3.8, 9.8, 4.4, 8.8],
[3.3, 7.6, 4.3, 8.5]])

grid, target, noisyDist

(array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), array([[0, 0],
        [0, 9],
        [9, 0],
        [9, 9]]), array([[ 6.3,  5.9,  5.5,  6.7],
        [ 5.6,  7.2,  4.4,  6.8],
        [ 7.6,  9.4,  4.3,  5.4],
        [ 9.5, 10. ,  3.7,  6.6],
        [ 6. , 10.7,  2.8,  5.8],
        [ 9.3, 10.2,  2.6,  5.4],
        [ 8. , 13.1,  1.9,  9.4],
        [ 6.4,  8.2,  3.9,  8.8],
        [ 5. , 10.3,  3.6,  7.2],
        [ 3.8,  9.8,  4.4,  8.8],
        [ 3.3,  7.6,  4.3,  8.5]]))

In [ ]:
# from itertools import product

# maxRow, maxCol = (10, 10)

# noiseList = np.array([[d1,d2,d3,d4] for d1 in range(7, 14)
#                 for d2 in range(7, 14)
#                     for d3 in range(7, 14)
#                         for d4 in range(7, 14)])*.1

# maxStep=11

# move = np.array([[1,0],[0,1],[0,-1],[-1,0]])

# path = np.intp([np.ones((maxRow, maxCol))*-1]*(maxStep+1))

# prob = np.float64([np.ones((maxRow, maxCol))]*(maxStep+1))

# for step in range(maxStep):
#     totalDist = 162.0
#     total=[]
#     for cell in product(range(maxRow), range(maxCol)):
#         row, col = cell
#         dist = np.sqrt(np.sum(np.square(target - [row,col]), axis=1))
#         best = []
#         bestDist = 162.0
#         for noise in noiseList:
#                         test = np.round(np.multiply(dist, noise)*10.0)/10.0
#                         if np.sum(np.square(test-noisyDist[step,:]))<bestDist:
#                             best=[noise,bestDist]
#                             bestDist = np.sum(np.square(test-noisyDist[step,:]))
#                         elif np.sum(np.square(test-noisyDist[step,:]))==bestDist:
#                             best.append(noise)

#         if bestDist<totalDist:
#             totalDist = bestDist
#             total = [row, col, dist, best, np.round(np.multiply(dist,best[0])*10)/10.0]

# #         print row, col, '---', dist, noisyDist[0,:], best

#     print step, 'total:', total, noisyDist[step,:]

In [64]:
np.multiply(np.array([ 5.        , 10.29563014,  4.        ,  9.8488578 ]),np.array([1.1, 0.7, 1.1, 0.7]))

array([5.5       , 7.2069411 , 4.4       , 6.89420046])

In [82]:
np.intp([np.ones((maxRow, maxCol))*-1]*2)

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [114]:
from itertools import product

maxRow, maxCol = (10, 10)

noiseList = np.array([[d1,d2,d3,d4] for d1 in range(7, 14)
                for d2 in range(7, 14)
                    for d3 in range(7, 14)
                        for d4 in range(7, 14)])*.1

maxStep=11

move = np.array([[1,0],[0,1],[0,-1],[-1,0]])

path = np.intp([np.ones((maxRow, maxCol))*-1]*(maxStep+1))

prob = np.float64([np.ones((maxRow, maxCol))]*(maxStep+1))

for step in range(maxStep):
    
    for cell in product(range(maxRow), range(maxCol)):
        row, col = cell
        if grid[row,col]!=1:
            continue
        
        if step>0:
            if row==0: 
                select=3
            else:
                select=0
            selectedStep = cell - move[select]
            for option in range(4):
                lastStep=cell-move[option]
                r, c = lastStep
                if r>-1 and r<maxRow and c>-1 and c<maxCol and grid[r,c]==1:
                        if prob[step-1][r][c]<prob[step][selectedStep[0]][selectedStep[1]]:
                            select=option
                            selectedStep = cell - move[select]
            path[step][row][col]=select
        
        dist = np.sqrt(np.sum(np.square(target - cell), axis=1))

        for noise in noiseList:
            test = np.round(np.multiply(dist, noise)*10.0)/10.0
            if np.sum(np.square(test-noisyDist[step,:]))<prob[step][row,col]:
                prob[step][row,col]=np.sum(np.square(test-noisyDist[step,:]))
                
        if step>0:
            select = path[step][row][col]
            selectedStep = cell - move[select]
            prob[step][row,col]*=prob[step][selectedStep[0]][selectedStep[1]]
            
    print 'Step ',step, prob[step]


Step  0 [[1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   0.67 0.23 0.06 1.   1.   1.   1.  ]
 [1.   0.99 1.   0.23 0.2  0.18 1.   0.31 1.   1.  ]
 [1.   0.7  1.   0.14 0.18 0.12 1.   0.91 1.   1.  ]
 [1.   1.   1.   0.09 0.22 0.15 1.   1.   1.   1.  ]
 [1.   1.   1.   1.   0.07 1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   0.51 1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]]
Step  1 [[1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00
  1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00]
 [1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00
  1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00]
 [1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00
  1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00]
 [1.000000e+00 1.000000e+00 1.000000e+00 1.40000

Step  10 [[1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [1.00000e+00 5.60000e-01 1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [5.00000e-02 1.35000e-02 1.00000e+00 2.10000e-01 5.40000e-01 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [1.15000e-02 2.70000e-03 1.00000e+00 3.78000e-02 2.04120e-02 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [4.25500e-03 8.10000e-04 1.00000e+00 2.87280e-02 2.04120e-02 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [4.12735e-03 8.10000e-04 1.00000e+00 2.87280e-02 2.04120e-02 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [4.12735e-03 8.10000e-04 8.10000e-04 2.87280e-02 2.04120e-02 1.00000e+00
  1.00000e+00 1.00000e+00 1.00000e+00 1.00

In [113]:
row = np.argmin(prob[maxStep-1])/maxCol
col = np.argmin(prob[maxStep-1])%maxCol

solution=[]
for step in reversed(range(maxStep)):
    solution.append((row,col))
    print row,col,path[step][row,col]
    row,col=np.subtract([row,col],move[path[step][row,col]])
    
solution=[(r,c) for r,c in reversed(solution)]
solution

5 1 0
4 1 3
5 1 3
6 1 1
6 0 0
5 0 3
6 0 0
5 0 0
4 0 3
5 0 0
4 0 -1


[(4, 0),
 (5, 0),
 (4, 0),
 (5, 0),
 (6, 0),
 (5, 0),
 (6, 0),
 (6, 1),
 (5, 1),
 (4, 1),
 (5, 1)]